### ISSUE TITLE
Embedded option setting

### ISSUE THREAD

**Issue by theothersideofgod** [ng-packagr/ng-packagr#1106]
## Type of Issue

```
[v] Bug Report
[ ] Feature Request
```

## Description

My library depend on highcharts.

After build , it shows below error

```
ERROR in ./libs/test-toolkit/fesm5/test-toolkit.js
Module not found: Error: Can't resolve 'highcharts' in '/ilabs/project/test-project/toolkit-test/libs/test-library/fesm5'
```

it seems ngpackagr didn't bundle highcharts for me.

ng-package setting as below

```
{
  "name": "test-library",
  "version": "1.0.0",
  "ngPackage": {
    "$schema": "../node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
      "entryFile": "index.ts",
      "embedded": [
        "highcharts"
      ],
      "umdModuleIds": {
        "highcharts": "Highcharts",
      }
    },
    "dest": "test-library",
    "whitelistedNonPeerDependencies": ["."]
  },
  "peerDependencies": {
    "@angular/animations": ">=6.0.0",
    "@angular/common": ">=6.0.0",
    "@angular/compiler": ">=6.0.0",
    "@angular/core": ">=6.0.0",
    "@angular/forms": ">=6.0.0",
    "rxjs": ">=6.0.0"
  },
  "dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/cdk": "^6.3.1",
    "@angular/common": "^6.1.6",
    "@angular/compiler": "^6.1.6",
    "@angular/core": "^6.1.6",
    "@angular/forms": "^6.1.6",
    "@angular/material": "^6.3.1",
    "@angular/platform-browser": "^6.1.6",
    "@angular/router": ">=6.0.2",
    "rxjs": "^6.3.2",
    "zone.js": "^0.8.26",
    "highcharts": "^6.1.4"
  },
  "devDependencies": {
    "highcharts": "^6.1.4",
  }
}

```

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

What should I do if I want to consumer using my library without install highcharts? 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.2.0
@angular/compiler:     6.1.8
rollup:                0.66.2
tsickle:               0.32.1
typescript:            2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

 "highcharts": "^6.1.4"

**Comment by alan-agius4** [comment]
Embed option is not longer available in ng-packagr v4. It was replaced with npm bundles dependencies 
https://docs.npmjs.com/files/package.json#bundleddependencies

I’ll try to document this a bit larger on today, however, I highly suggest that you use peerDependencies instead.

**Comment by dherges** [comment]
Hi all,

my personal experience: I would not use bundledDependencies nor embedding any more. In the first place, we were using it for proprietary non-public third party dependencies. Why we eventually were comfortable with it? Because of the architecture/environment in which our applications and libraries were running we were safe to not have conflicting versions - actually, we were 'forced' to embed the proprietary code because we didn't want to expose it to public APIs. If that's the case, it's the only use case I think of where it's ok to do embedding/bundling. (In the meantime, we changed the architecture and don't do it anymore)

For most (every) open source project I'd recommend to use peerDependencies. Give your consumers some choice: choice to resolve version conflicts, choice to use or to not use dependency APIs directly.

**Comment by theothersideofgod** [comment]
Hi, alan-agius4, dherges
Thank you very much for you guy's reply.
so when consumer use my library, they will need to install highcharts again if I bundled highcharts by peerdependancy, right?

**Comment by alan-agius4** [comment]
Yes indeed

**Comment by shadizar128** [comment]
Hi,

I'm getting the following warning when  I use 'bundledDependencies':

> Inlining of 'bundledDependencies' has been deprecated in version 5 and will be removed in future versions.

What is the alternative? If we use 'peerDependencies' the final UMD file will not contain the required dependencies.

**Comment by jps1st** [comment]
It seems to me that some dependencies prefer to have their source bundled with your code. I wanted to include ol (open layers)  and uuid in my library since they don't have UMDs like other ng libs in my node_modules. Removing bundledDependencies seems like not allowing using external source files in this nature anymore.
