### ISSUE TITLE
Include *.json files

### ISSUE THREAD

**Issue by beradrian** [ng-packagr/ng-packagr#1131]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

#### How To Reproduce

I added to `tsconfig.json`
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
but I got the error

> ng-packagr -p ng-package.json
> 
> Building Angular Package
> Building entry point '@nibo/nibo-ui'
> Compiling TypeScript sources through ngc
> 
> BUILD ERROR
> src/app/my.ts(6,15): error TS2732: Cannot find module '../assets/x.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

#### Version Information
I upgraded to 
ng-packagr 4.4.0
Angular 7.0.0
Typescript 3.1.1
rxjs 6.3.3
node 8.11.1
npm 6.4.1

**Comment by alan-agius4** [comment]
You need to provide a tsconfig via the command line using the `-c`.

By default we are not enabling `resolveJsonModule` as this is only available for advance users. 

Main reason is that while json files are now supported, it is more for an advance users usages as this features comes with some downsides. One of them being that it won't work in the browser without any module bundler.

**Comment by vonmutinda** [comment]
Add the following configurations to 'tsconfig.json' file:

```bash
"resolveJsonModule": true,
"esModuleInterop": true,
"allowSyntheticDefaultImports": true
```

**Comment by sebastien-p** [comment]
Hi.

In my case this doesn't work.

I mean using `resolveJsonModule` works but compiling imported JSON files doesn't because, when the `annotateForClosureCompiler` [flag](https://angular.io/guide/angular-compiler-options#annotateforclosurecompiler) is set to `true`, [tsickle](https://github.com/angular/tsickle) adds comments at the top of my JSON files breaking some internal `JSON.parse` call, only printing me those two error lines in the end:

```
ERROR: Unexpected token / in JSON at position 0
An unhandled exception occurred: Unexpected token / in JSON at position 0 
```

Literally lost my whole day debugging this, I bet you have no idea how stupidly hard it was.

Now if I set `annotateForClosureCompiler` to `false` it works as expected but I get no tree shaking and stuff...

Does anyone have a clue on how to actually fix this?

Thanks

**Comment by alan-agius4** [comment]
Closure compiler doesn't support JSON as JS modules and thus `annotateForClosureCompiler` will not work with `resolveJsonModule`.

See: https://github.com/angular/tsickle/pull/922

**Comment by sebastien-p** [comment]
@alan-agius4 yes, that I found out the hard way. Are you saying that there's nothing I can do to import JSON files without losing tree shaking?

**Comment by alan-agius4** [comment]
You don't loose tree-shaking if you set `annotateForClosureCompiler` to `false`.

**Comment by sebastien-p** [comment]
I mean this flag must be here for a reason. I checked the build bundle and saw that my whole JSON file was there even if I destructured only one field. I believe last time I did that in an Angular app I only got the destructured field and nothing else in the built bundle.

**Comment by alan-agius4** [comment]
It was turned on to fix issues with `forwardRef` and since than it has been turned off. And in version 9 all libraries will be migrated to have `annotateForClosureCompiler` turned off.

See: https://github.com/angular/angular-cli/pull/15603

**Comment by sebastien-p** [comment]
Nice, thank you very much :)
