### ISSUE TITLE
Setting prerequisite for package

### ISSUE THREAD

**Issue by bhuvaneshwari** [ng-packagr/ng-packagr#1135]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

We should be able to set pre requisite to the packaged tarball, such that npm install can throw an error while installing. My module has a dependency module which requires minimum Angular 6. I want to configure so that an error is thrown while npm installing my package when the @angular/cli version in the target project node_modules is less than 6. 

If there is already a way, how to do that? I might have missed something. Any suggestions appreciated.

#### Expected Behaviour

I'm not sure of implementation solution. I do know that it would be very convenient to make npm install fail if the pre requisite module version isn't installed.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.2.0
@angular/*: 6.1.5
typescript: 2.7.2
rxjs: 6.3.2
node: 8.11.4
npm: 6.4.1
```

**Comment by alan-agius4** [comment]
I don’t think that something like that should be in the domain of ng-packagr. If you want to add something like that you need to do it as a post or perinatal script. However, that said it’s not something that I’d suggest you to do. As strictly speaking when installing your users already get a warning that they have unmet deps since you should be using peerDeps.
