### ISSUE TITLE
Secondary Entry Points build fail

### ISSUE THREAD

**Issue by raphael-volt** [ng-packagr/ng-packagr#1201]
## Type of Issue

```
[ ] Bug Report
```

## Description

I try to create a library with a secondary entry point as explained in the doc, but I can't built it.

#### How To Reproduce

Clone this repository [secondary-entry-points-build-fail](https://github.com/raphael-volt/secondary-entry-points-build-fail.git) then try to build the library.

#### Expected Behaviour

Make it easier to create scoped libraries by providing an example with source code.

#### Version Information

```
ng-packagr:            4.7.0
@angular/compiler:     7.1.4
rollup:                0.67.4
tsickle:               0.34.0
typescript:            3.1.6
```

**Comment by alan-agius4** [comment]
The problem is here https://github.com/raphael-volt/secondary-entry-points-build-fail/blob/master/projects/my-package/src/lib/my-package.component.ts#L2

Dependencies between entrypoints should be referenced using the packages as these should be treated as different modules. Hence change;
```
import { TESTING } from "../../testing/src/testing";
```

to 

```
import { TESTING } from "my-package/testing";
```

Also, note that it seems that you are building you app before the lib from the error in the repo readme. `ERROR in src/app/app.component.ts(3,25): error TS2307: Cannot find module 'my-package/testing'.`

You always need to build the library before the application example
```
ng build my-package
ng build
```
