### ISSUE TITLE
increase speed with incremental builds in dev mode

### ISSUE THREAD

**Issue by LPCmedia** [ng-packagr/ng-packagr#1222]
## Type of Issue

```
[ ] Bug Report
[ X ] Feature Request
```

## Description

As an Angular dev using monorepos with multiple libs I need incremental builds to be faster. 

Given an Angular application: **app** that consumes an angular library: **lib** using ng-packgr to build.

When working in "dev mode", a.k.a incremental builds with a watch option, the recompilation is not fast enough. This causes additional issues when working with a monorepo where the **lib** is built and linked to an **app**. The **app** is recompiled several times as ng-packagr writes the various formats prescribed by the Angular Package Format and reloads several times.

#### Proposed solution

*This was done with a simple fork of the project and the results are astonishing.*

Add means to limit the generated formats as needed by the application consuming the library. This would apply to "dev" mode only.

- ability to disable UMD module generation.
- ability to set the "Flattened" ecmascript module type with an argument that specifies ES2015 | ES5 or both. this depends on what the app is using in the typescript compiler options. 
- *.metadata.json and *.d.ts files would always generated.

#### Additional Info

We were able to implement this by forking the latest version 4.7.1 and the improvements are significant. The **app** still recompiles occasionally but not as often. This could also be resolved but would be a second improvement on this "selective" Angular Package Format watch mode. 

My team and I are willing to contribute to build this feature but would need some guidance on the implementation details should this be a fit with ng-packagr.

- should we add a second command in "bin" for dev mode ?

  ng-packagr-dev -p ng-package.json —no-umd <—ES5 | --ES2015 >

- should this be implemented with additional command line arguments ?

- should this be configurable in package.json

*What implementation would be acceptable and documentation needed as this derives from the official "Angular Package Format" ?*

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.7.1
@angular/*: 7.1.*
typescript: 3.1.6
rxjs: 6.4.0
node: 10.15.1
npm: 6.8.0
```

Version Information

**Comment by LPCmedia** [comment]
@IgorMinar and @jasonaden any thoughts on this ? Can we skip generation of some artefacts to speed up development ?

**Comment by alan-agius4** [comment]
Hi @LPCmedia, thanks for reaching out. 

The refreshing that you are seeing are causing because ng-packagr writes directly to disk, during every part of the compilation. The solution for this would be to write to an in memory cache and only emit the files to disk at the very end of the pipeline.

While the above might work for your use case, I am not very keen, into extending the options provided, as with this approach, users would need to have a certain amount of knowledge of which type of bundles their application/testing framework depends on. If for example, one is testing universal they would need to also include UMDs, same things apply for some testing setups such as jest.

Also this would mean more code to maintain as new logic would need to be introduced to determine what needs to be built. 

Since at the moment;
1) DTS and metadata generation is only generated in the ES2015 part of the compilation.
2) Generation of UMD bundles, are based on an ES5 compilation.

I would avoid adding an addition bin, also ideally new features should be available via the API as well.

That said my suggestions would be;
1) Use an in memory file system and write the outputs at the end of the compilation. This is the ideal solution for the problem you are facing.
2) Benchmark the build and see what's taking so long, and address those.

**Comment by zladuric** [comment]
@LPCmedia you say you've done this with a project fork. Care to share the fork? I'd love to take it for a spin myself, I think adding _some_ way to achieve this should be possible.

As for the second comment - if the "unskilled" people use the non-default options, then yeah, there might be a way to warn them about it. The build process as it is is quite slow, and I really think there needs to be a way to improve it. Just need to find a way to do this without much pain for the uninitiated :)

**Comment by dherges** [comment]
I like the idea. What if...

1. ...adding a `-dev` flag to ng-packagr?

```bash
$ ng-packagr -p ng-package.json --dev
```

Build pipeline could skip rollup, could skip es5 downlevelling, could skip metadata generation. Is `ng serve` resolving `import * from '@foo/bar'` to `dist/esm5/<entryFile>.js`?


2. ...adding an in-memory file system?

Let's go through the "The File System Is The API" discussion again 😂  

https://www.solitr.com/blog/2014/02/broccoli-first-release/

**Comment by alan-agius4** [comment]
At the moment `ng serve` itself at the moment uses FESM5 or FESM2015, based on what type of compilation target you have set in your application tsconfig. Eventually this will change with differential serving as users will have an addition flag to support es5 browsers or not.

Which js sources are loaded is based on what’s configured in `module` and `es2015` in `package.json` as per the APF spec.

If users are using `jest`, `universal` etc it’s based on the `main` field hence uses `umd` bundle.

**Comment by brian428** [comment]
All of the earlier suggestions sound great, but honestly if we could just conditionally skip the minification that would probably speed things up a **lot**, especially for larger libraries.

**Comment by LPCmedia** [comment]
I'll be looking into this in the next couple days.

**Comment by MrFrankel** [comment]
@LPCmedia any progress on this? we are facing a similar issues and would happy to help too!

**Comment by redjab** [comment]
It's pretty simple to modify the code to not produce any bundles you don't want (it's the write-bundles.transform & compile-ngc.transform files), but it's still rather slow to rebuild libraries, especially when you have a lot of dependencies depending on each other (i.e: A -> B -> C, so when you change something in A, A has to rebuild, then B, then C, which is very slow and prone to crashes). 

What I've done instead is follow the approach nrwl/nx is doing for our dev environment -- so that locally, we always run serve using the source .ts files. For our production/ test / ci environment, we're doing the ng-packagr way where you build each dependency separately. 

The disadvantage of the above approach is sometimes things can work in dev but not in the ci environment, but that's why we have our ci tools to prevent merging until those issues have been fixed.

**Comment by thescientist13** [comment]
Would be super happy to help  out / review on this as well.  This would certainly be a useful feature for our organization.

**Comment by petermikitsh** [comment]
It looks like @LPCmedia's work is contained in this commit: https://github.com/LPCmedia/ng-packagr/commit/36214363b557a4a66fc4bf592b863e035d11b3f6

I'm also interested in achieving the issue title's stated goal: faster (incremental) builds. As a regular user of bundlers, I'm quite familiar with one of the bottlenecks being minification of code. For users writing libraries, minifcation is not a concern in development mode. Libraries should simply be ES5 code (with ES Module `import` syntax or `require`, depending on your needs).

If anyone is looking to just transpile (with watchers) you can install `@angular/compiler-cli` and then run `./node_modules/.bin/ngc -w`. On a small project, transpiling with `ngc` takes 5 seconds to run. With watchers enabled, incremental rebuilds are about a second. Those numbers put a floor on how fast a build / incremental build can be-- getting improvements beyond these would require work on Angular's compiler. Bundling and minifying will only add more time.

**Comment by sbradl** [comment]
Are there any updates on this? I would also highly appreciate faster build times :)

**Comment by alan-agius4** [comment]
With v10 build time should be improved because of 2 less formats to builds.

We are also experimenting with more caching, but this has a downside that builds will require more memory.

**Comment by cdllqos** [comment]
> With v10 build time should be improved because of 2 less formats to builds.
> 
> We are also experimenting with more caching, but this has a downside that builds will require more memory.

@alan-agius4 
src/lib/ng-package/entry-point/write-bundles.transform.ts
```typescript
// Add UMD module IDs for dependencies
  const dependencyUmdIds = entryPoint
    .filter(isEntryPoint)
    .map((ep) => ep.data.entryPoint)
    .reduce((prev, ep: NgEntryPoint) => {
      prev[ep.moduleId] = ep.umdId;

      return prev;
    }, {});

  const { fesm2015, esm2015, umd, umdMinified } = destinationFiles;

  const opts = {
    sourceRoot: tsConfig.options.sourceRoot,
    amd: { id: ngEntryPoint.amdId },
    umdModuleIds: {
      ...ngEntryPoint.umdModuleIds,
      ...dependencyUmdIds,
    },
    entry: esm2015,
    dependencyList: getDependencyListForGraph(graph),
  };

  log.info('Bundling to FESM2015');
  await rollupBundleFile({
    ...opts,
    moduleName: ngEntryPoint.moduleId,
    format: 'es',
    dest: fesm2015,
  });

  log.info('Bundling to UMD');
  await rollupBundleFile({
    ...opts,
    moduleName: ngEntryPoint.umdId,
    entry: esm2015,
    format: 'umd',
    dest: umd,
    transform: downlevelCodeWithTsc,
  });

  log.info('Minifying UMD bundle');
  await minifyJsFile(umd, umdMinified);
```
Above the code, it still build two formats,  but only one format needed when we developing. And also it calls `minifyJsFile`, I think it effects build performance. So I hope there is a way to provided for config builds package formats. Maybe like this:
ng-package.json
```json
{
  "xxx":"xxx",
  "packageFormat": ["fesm2015"]
}
```

**Comment by alan-agius4** [comment]
@cdllqos, can you please provide some timings for your project for each step when running in incremental mode?

**Comment by cdllqos** [comment]
Its costs 12s-13s each step

**Comment by alan-agius4** [comment]
I have a PR in flight (https://github.com/ng-packagr/ng-packagr/pull/1704) which should help improve incremental builds quite a lot, if the problem persists after updating, kindly provide the exact timings for each steps, and more information about your library size.

Thanks.

**Comment by LPCmedia** [comment]
with v10 the original idea is no longer required.

**Comment by LPCmedia** [comment]
@alan-agius4  guess I can close this ?

**Comment by alan-agius4** [comment]
Yeah i think so
