### ISSUE TITLE
Modify library package.json (do not copy to dist folder)

### ISSUE THREAD

**Issue by dherges** [ng-packagr/ng-packagr#1229]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Do not copy/write an additional `package.json` in the dist directory.

#### Current Behaviour

`package.json` is copied from source folder to `dist` folder.

Publish workflow is `cd dist && npm publish`

#### Expected Behaviour

`package.json` is validated whether generated artefacts are references (properties `main`, `typings`, and so on). If properties in `package.json` are missing (or pointing to wrong location), `package.json` will be updated with correct properties.

Optionall, an [`.npmignore` files](https://docs.npmjs.com/misc/developers) is generated to exclude source files from the npm package.

Publish workflow is `npm publish` in current working directory.

Library `package.json` would look like:

```json
{
  "name": "@foo/bar",
  "version": "1.0.0",
  "typings": "./dist/typings/foo-bar-api.d.ts",
  "main": "./dist/<path-to-js-bundle>",
  "module": "./dist/<path-to-js-bundle>",
  /* .. */
}
```

Secondary entry point `package.json` would also need to be validated and updated. Example would look:

```json
{
  "name": "@foo/bar/bla/blubb",
  "typings": "../../dist/typings/foo-bar-api.d.ts",
  "main": "../../dist/<path-to-js-bundle>",
  "module": "../../dist/<path-to-js-bundle>",
  /* .. */
}
```

#### Version Information

```
ng-packagr: 6.x
```

**Comment by dherges** [comment]
What places are going to break?

**Comment by alan-agius4** [comment]
In CLI, 

1) `ng serve` / `ng build` will indeed break.
2) need to add these sub `dist` folders to `.gitignore` as previously the dist was in the workspace root.
3) CLI path mappings
4) CLI E2E and integration specs

**Comment by macjohnny** [comment]
would this allow to have `"private": true` in the `package.json` and not have it in the `dist/package.json`?

**Comment by alan-agius4** [comment]
The request here, is that you publish from the root and you won’t have a package.json  in dist.

Hence, the answer to your question will be no.

**Comment by nategreen** [comment]
I see the "community: discussion" tag...what are you looking for feedback on?

**Comment by alan-agius4** [comment]
Feedback I guess from the community. And afterwards decide if we’ll go with it or not.

At this point in time, i’d say it’s more of a no.

**Comment by nategreen** [comment]
My 2 cents as I'm more familiar with Node/npm than with Angular (and not an expert in either one): **I would at least like to see this be an *option***.

I tend to agree with [lerna's maintainer](https://github.com/lerna/lerna/issues/1282), that compiling to a separate/duplicate package seems like a Node/npm anti-pattern—even if _that's_ debatable, compiling to a separate place/package could be said to be an *opinionated* workflow, right?

From my perspective, trying to set up a design system with Angular components but also *other*, non-Angular npm packages, it seems like that opinionated piece is what's making it hard to get everything up and running. Since ng-packagr and Angular CLI are ostensibly the bridge between an Angular-formatted project and a Node/npm-formatted package...I would (and did) expect to be able to use other Node/npm tools like lerna to work with the resulting packages, without all the fiddling/working-around that's currently required. Again, just my 2 cents, though, and I'm certainly not an authority on Angular, lerna, NPM, or any of it.

**Comment by alan-agius4** [comment]
Thanks all for the input.

However, I am closing as this is not in the roadmap anymore  and lerna now supports publishing from a subfolder.
