### ISSUE TITLE
How to analyze generated bundle

### ISSUE THREAD

**Issue by thedewpoint** [ng-packagr/ng-packagr#1249]
## Type of Issue
```
[ ] Bug Report
[ ] Feature Request
[X] Question

```

## Description

Is there a way to do bundle analysis on this code? I know that the consuming app would take care of the tree shaking and bundling, but when I do bundle analysis on my consuming web applications, the biggest module that I am consuming is my own component library (which is relatively small from a code perspective). Its a navigation header component, but for some reason after bundling, it is the largest thing in my application. Is there a way for me to generate a stats-json or something similar so i can analyze what the biggest part of my code is? My current theory is maybe it is the CSS being embedded.

Thank you!

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.1

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Hi, this is interesting but at the moment there is no way of analysing such information.

This is because a size of a library can vary based on minification and tree-shaking that are applied upon consumption. 

What you can make sure of is if you library is side effect free using this tool: https://github.com/filipesilva/check-side-effects#readme
