### ISSUE TITLE
Import relative dependency inside lerna monorepo causes `Cannot find module` error

### ISSUE THREAD

**Issue by uNmAnNeR** [ng-packagr/ng-packagr#1349]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I want to use `ng-packagr` inside monorepo but getting `Cannot find module ...` error:

https://travis-ci.com/uNmAnNeR/imaskjs/builds/120659784#L389

it seems that `ng-packagr` does not consider typescript `paths` option.

#### How To Reproduce

Here is what was done: https://github.com/uNmAnNeR/imaskjs/pull/223

#### Expected Behaviour

import relative dependency with no errors

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.3.0
@angular/*: 8.1.2
typescript: 3.4.5
rxjs: 6.5.2
node: 12.6.0
npm/yarn: 6.10.1
lerna: 3.16.4
```

**Comment by listepo-alterpost** [comment]
@alan-agius4 any thoughts?

**Comment by alan-agius4** [comment]
You need to add typings for `imask` since they don’t have typings. Also the path mapping seems to be pointing to an non exiting files.

Check this spec to see how to do it https://github.com/ng-packagr/ng-packagr/tree/master/integration/samples/typings/src

**Comment by alan-agius4** [comment]
Actually looking at it again, the file exists.

**Comment by alan-agius4** [comment]
Okay, it seems that you are not using The tsconfig defined.

This is because the tsconfig path is not being provided here:
https://github.com/uNmAnNeR/imaskjs/blob/8824f195660ad91602b94e2796bbb0ba586b8b8e/packages/angular-imask/package.json#L12

You need to provide the tsconfig path via `—config` as otherwise ngpackagr
will use its internal tsconfig by default

**Comment by uNmAnNeR** [comment]
@alan-agius4 seems working, thanks!
