### ISSUE TITLE
Rollup 1.26 breaks fesm5 build of libraries

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#1431]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

`ng-packagr` declares a dependency on `rollup` that includes version `1.26.0`. With this version we see that the `fesm5` build of our library contains * exports. 

I think that this is related to https://github.com/rollup/rollup/issues/3196

This basically breaks the build of all of our libraries. 

I suggest to set the dependency of `ng-packagr` to `rollup@~1.25` until rollup fixes the bug.

**Comment by DannyRussellWP** [comment]
+1 this has broken all of my build too. It appears to be being pulled in automatically as i haven't updated to the new version. I'm still on 5.4 and am still having this issue. Is there a workaround?

**Comment by jpspringall** [comment]
@danny,

That's strange, we 'fixed' by downgrading to 5.4.3 and that worked for us.

The other thing that worked for us to add a dependancy to rollup 1.25.2 in your package.json, if you are using npm rather than yarn as it didn't work for us with yarn.

Finally if you keep the lock files you could update that to point to 1.25.2. Though i guess you've not got a lock file, otherwise you'd already be pinned to another version.

Cheers

James

**Comment by alan-agius4** [comment]
Indeed this issue is caused by https://github.com/rollup/rollup/issues/3196

Will lock the rollup and cut a release tomorrow morning CET.

**Comment by DannyRussellWP** [comment]
Thanks James. Yes 5.4 for me just was pulling in ^1.12.0

I know we should have lock files, but we are actually using the openapi generator for angular typescript so the package files are being generated automatically.

Another example of almost too much automation

________________________________
