### ISSUE TITLE
Reopen #1080 - Bundle format configuration

### ISSUE THREAD

**Issue by Hobart2967** [ng-packagr/ng-packagr#1557]
See #1080.

In my opinion this should be configurable though. We for example use ng-packagr for internal use, which means that there's no public rollout of the packages (plugins for a big host). The host only accepts umd. Therefore it's totally non-sense to build all the formats.

**Comment by alan-agius4** [comment]
With APF version 10, the built output will most likely change, so currently there is no plan to extend the API knowing that we'd need to break it relatively soon.

To build the UMD you'd still need to go through most of the building process of ES5 bundles, because the UMD bundle is generated from the ES5 output.

Let's reconsider this post version 10. Thanks.

**Comment by vasicvuk** [comment]
@alan-agius4 Is this plan for version 10?

In my case i want to build UMD only because i am using it as Plugin loaded in Ivy not for publishing to NPM. Full build now takes 5 minutes or so and UMD only with Rollup and TSC builds in seconds.
