### ISSUE TITLE
Conflicting Namespaces

### ISSUE THREAD

**Issue by fireflysemantics** [ng-packagr/ng-packagr#1564]
## Type of Issue

```
[ x] Bug Report
```

## Description
ole@mkt:~/Github/validatorjs-workspace$ npm run p

WARNING: Conflicting namespaces: dist/validatorts/esm2015/public-api.js re-exports 'ɵ0' from both dist/validatorts/esm2015/lib/validators/isIdentityCard.js and dist/validatorts/esm2015/lib/validators/isISO8601.js (will be ignored)

> validatorjs-workspace@0.0.0 p /home/ole/Github/validatorjs-workspace
> cd projects/validatorts && bump patch && cd ../.. && npm run b && cd dist/validatorts && npm publish

✔ Updated package.json to 12.2.30
✔ Updated package-lock.json to 12.2.30

> validatorjs-workspace@0.0.0 b /home/ole/Github/validatorjs-workspace
> ng build validatorts

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@fireflysemantics/validatorts'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
WARNING: Conflicting namespaces: dist/validatorts/esm2015/public-api.js re-exports 'ɵ0' from both dist/validatorts/esm2015/lib/validators/isIdentityCard.js and dist/validatorts/esm2015/lib/validators/isISO8601.js (will be ignored)
Bundling to FESM5
WARNING: Conflicting namespaces: dist/validatorts/esm5/public-api.js re-exports 'ɵ0' from both dist/validatorts/esm5/lib/validators/isIdentityCard.js and dist/validatorts/esm5/lib/validators/isISO8601.js (will be ignored)

#### How To Reproduce

```
git clone https://github.com/fireflysemantics/validatorts
cd validatorts
npm run u
npm run p
```

```
$ node_modules/.bin/ng-packagr --version

```
ng-packagr:            9.0.2
@angular/compiler:     9.0.4
rollup:                1.31.1
tsickle:               
typescript:            3.7.5

```

**Comment by jupin-r** [comment]
I have same issue. Conflict is for constant which is not exported.

**Comment by hitallow** [comment]
I have same issue.

**Comment by alessiostalla** [comment]
I have it too.

**Comment by xiaoxiangmoe** [comment]
I have it too.

**Comment by SchnWalter** [comment]
This seems to be related to code that isn't exported, and the issue is also present with the latest dependencies.

In the linked, if you export `const isValidDate = (str) => ...` from [isISO8601.ts#L7](https://github.com/fireflysemantics/validatorts/blob/09f1344f9ee9e51ab0749d3476090f2af5611a6a/projects/validatorts/src/lib/validators/isISO8601.ts#L7), then the error goes away. But that function constant is only for internal use, so maybe you could either avoid using `export * from` instead of exporting that validator. What's even more strange, the functions that exist as object properties in `isIdentityCard` are also exported, even though they are only used inside that file.

This is probably an issue with the angular compiler and not ng-packagr. Maybe related to related? https://github.com/angular/angular/issues/33668
