### ISSUE TITLE
[Question] How do we exclude tslib as a peer dependency?

### ISSUE THREAD

**Issue by fireflysemantics** [ng-packagr/ng-packagr#1565]
## Type of Issue

```
[ X] Feature Request
```

## Description
Provide a way to exclude `tslib` being generated as a peer dependency.

## Stackoverflow Question

https://stackoverflow.com/questions/60628698/do-we-need-the-angular-library-tslib-peer-dependency-when-publishing-a-library

**Comment by alan-agius4** [comment]
Actually, you do use `tslib` you just don't realise this since you need to check the output of the library
https://unpkg.com/browse/@fireflysemantics/validatorts@12.2.31/fesm5/fireflysemantics-validatorts.js

That is because if you use `importHelpers` tslib will be used. https://github.com/microsoft/tslib
