### ISSUE TITLE
import some scss files into library component scss throw errors

### ISSUE THREAD

**Issue by robertIsaac** [ng-packagr/ng-packagr#1631]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

when trying to import bootstrap mixins @import "~bootstrap/scss/mixins"; it throw the following error ERROR: Can't find stylesheet to import.

#### How To Reproduce

clone
https://github.com/robertIsaac/scss-reproduce
run ng build

#### Expected Behaviour

to build successfully

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            9.1.3
@angular/compiler:     9.1.4
rollup:                2.7.5
tsickle:
typescript:            3.8.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

bootstrap: 4.4.1

## notes
this is created by suggestion of https://github.com/angular/angular-cli/issues/17660#issuecomment-625194173

i do another two imports and they are working fine
```
@import "~boosted/scss/functions";
@import "~boosted/scss/variables";
@import "~boosted/scss/mixins";
```

and changing the import to 
`@import "~boosted/scss/_mixins";` will make the build run successfully

it can be related to that there is a directory named `mixins` inside the bootstrap/scss directory, it's just a a guess

**Comment by Sapendo** [comment]
Any updates?

**Comment by lars-berger** [comment]
The issue is that ng-packagr doesn't respect the `sass` property in Bootstrap's `package.json`.

Take for example an NPM package that has a `package.json` which looks like this:

```JSON
{
  "name": "@my-app/styles",
  "version": "1.0.0",
  "sass": "src/main.scss"
}
```

If you attempt to consume that library within an ng-packagr library, it won't work.

```
// app.component.scss

@import '~@my-app/styles'; // <-- Will throw 'ERROR: Can't find stylesheet to import.'
@import '~@my-app/styles/src'; // However, this will work.
```

This gets even more hacky if you want to use the modern `@use` syntax, since the namespace changes (eg. `@use '~@my-app/styles/src' as styles;`).

Angular does in fact respect the `sass` property, which creates inconsistencies between how stylesheets are imported in libraries vs. apps.

**Comment by flash-me** [comment]
@robertIsaac 
You got it right, for the path `scss/mixins` the Sass compiler will both for `sass/mixins` & `sass/_mixins` as described [here](https://sass-lang.com/documentation/at-rules/import#partials).
Since there is also a `mixins` [folder](https://github.com/twbs/bootstrap/tree/main/scss/mixins), sass tries to load from there but cannot find an [index](https://sass-lang.com/documentation/at-rules/import#index-files) file which seems to cause the error.

Besides correctly using `sass/_mixin` you have also the option to add the file extension to make it more verbose: `sass/mixin.scss`

@lars-berger I'm not sure why this is an issue, tho. You are free to write whatever you want in your `package.json`. Doesn't mean that everyone else needs to consider that. The same like with the support for `~` imports. These non-standard things need to be implemented first, by developers, which requires time, because some other folks are not ready to use standards.

The `@use` approach is well documented and it's been known for a long time that the `@import` will be [deprecated](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline)


cheers
flash ⚡

**Comment by lars-berger** [comment]
@flash-me  It's an issue because it's a convention that Angular follows, but ngpackagr does not. Respecting the `"sass"` property is expected behavior, which is why this bug report was created in the first place

**Comment by flash-me** [comment]
1. Bootstrap is the only more or less known package having that property. Not even tailwind as the newcomer has a 'sass' property in the package.json. So I really don't know which convention you are referring to. 
2. I'm pretty sure angular never explicitly insisted on that non-standard feature. This whole thing comes with webpack and/or the used sassloader. More on that [here](https://github.com/webpack-contrib/sass-loader/issues/535)

The sass specs clearly define how the Importing is handled. 
Said that, this is not a bug report. It's a request for a non standard feature. Only to support one library.

cheers
flash ⚡

**Comment by lars-berger** [comment]
@flash-me Tailwind uses the `"styles"` property, which is just an alias for `"sass"` (more common among CSS libraries, since it doesn't even use SASS). You'll find that pretty much every CSS/SCSS library has a `"sass"` or `"styles"` in their package.json. Not to mention there's also people who use monorepos and run into into this issue when separating their stylesheets into a library (my personal use case).

**Comment by flash-me** [comment]
@lars-berger 
The specifications of [package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#main) neither mention "styles" nor "sass".

The Sass compiler gives you the ability to declare [Load Paths](https://sass-lang.com/documentation/at-rules/import#load-paths), which is also supported by ng-packagr. Even more, it's supposed to be used for exactly the same use case as yours. 

cheers
flash ⚡

**Comment by nhhockeyplayer** [comment]
why cant this be fixed?
who is holding down this repo?
this should have been part of the functionality prior to this even being public
is the code that brittle?

**Comment by Wlada** [comment]
Any workaround for this issue?
