### ISSUE TITLE
Alternative to bundledDependencies

### ISSUE THREAD

**Issue by hypery2k** [ng-packagr/ng-packagr#1739]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```
With in the [changelog](https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md#breaking-changes-5) bundledDependencies is mentioned for replacing embedded option, but the option is deprecated

## Description

If I build my library with bundledDependencies I'm getting following error:

```
------------------------------------------------------------------------------
Building entry point '....'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
WARNING: Inlining of 'bundledDependencies' has been deprecated in version 5 and will be removed in future versions.
List the depedency in the 'peerDependencies' section instead.
```

#### How To Reproduce

see above.

#### Expected Behaviour

Have no warnings

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            10.0.2
@angular/compiler:     10.0.4
rollup:                2.10.9
tsickle:
typescript:            3.9.7
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by SchnWalter** [comment]
`peerDependencies` is now the recommended way to add dependencies, see [docs/dependencies.md](https://github.com/ng-packagr/ng-packagr/blob/v10.1.0/docs/dependencies.md) and this commit:

> feat: deprecate inlining of `bundledDependencies`
> List the depedency in the "peerDependencies" section instead.  
> https://github.com/ng-packagr/ng-packagr/commit/0c52486

**Comment by hypery2k** [comment]
is there any alternative to include certain external dependencies directly into a library?

**Comment by SchnWalter** [comment]
AFAIK `ng-packagr` doesn't provide an alternative. But there is no need to directly include your dependencies, in fact, it should be avoided because it makes build optimizers less efficient and this is discouraged.

If your intention is to lock onto a certain version of a library, you can either do that by using a fixed version in `peerDependencies`, but this requires the library consumer to install that dependency. Alternatively, you could start using `dependencies`, and for this, the package manager will automatically install the dependency when the library is installed, no action required from the library consumer.

**Comment by hypery2k** [comment]
ok got it. Thought about having something like a "pre-optimized" package with all needed parts included

**Comment by SchnWalter** [comment]
If you "pre-optimize" a library, the final optimizations won't be as good when more libraries are included. And since you are using `ng-packagr` to ship libraries that will be processed by the Angular CLI, there's no need to "pre-optimize" a library, the CLI can do that at a later point and it will do it better than if you do it when the library is built. Also, `ng-packager` just packs the code in the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview), and it doesn't do any optimizations at all.

**Comment by alan-agius4** [comment]
Closing as per the above comment and docs https://github.com/ng-packagr/ng-packagr/blob/v10.1.0/docs/dependencies.md explaining why not using `peerDependencies` can cause increase in bundle size.

Thanks @SchnWalter  for responding to this.
