### ISSUE TITLE
Confusing error "WARNING: No name was provided for external module 'xxx' in output.globals – guessing 'xxx'" for absolute imports

### ISSUE THREAD

**Issue by LastDragon-ru** [ng-packagr/ng-packagr#1757]
## Type of Issue

```
[x] Bug Report
[x] Feature Request
```

## Description

When you use absolute imports inside lib you will get an absolutely confusing warning "No name was provided for external module 'xxx'". 

#### Desired Behaviour

1. Add supports for absolute imports (related to #916). IMO this is much much better because 
    - angular supported it
    - in a big app 'path/to/Component' much more readable than `../../../../../../../../../../../../Component`
    - mixed style is also confusing
2. Show smart warning eg "Absolute imports don't support, please use relative."

#### Version Information

```
ng-packagr:            10.1.2
@angular/compiler:     10.1.3
rollup:                2.28.2
tsickle:
typescript:            4.0.3
```

**Comment by flash-me** [comment]
Usually you get this error by importing external modules / library  in your library. 

cheers
flash ⚡

**Comment by youqing-voyager** [comment]
> Usually you get this error by importing external modules / library in your library.
> 
> cheers
> flash ⚡

But this warning not only if you import external modules, it also show when you import your own code from a absolute path.

**Comment by flash-me** [comment]
Absolute Paths can be achieved with tsconfig.json and the corresponding path mapping.

If this does not work, you may provide a repository with the according example, where the behavior can be reproduced. 

cheers
flash ⚡

**Comment by LastDragon-ru** [comment]
>  If this does not work, you may provide a repository with the according example, where the behavior can be reproduced.

https://github.com/LastDragon-ru/ng-packagr-1757 + `ng build my-lib`

**Comment by JoostK** [comment]
> > Usually you get this error by importing external modules / library in your library.
> > cheers
> > flash ⚡
> 
> But this warning not only if you import external modules, it also show when you import your own code from a absolute path.

It is generally a good idea to only use relative imports within a single entry-point, and only use absolute imports for other entry-points or libraries. Tooling such as ngcc uses heuristics to determine whether an import constitutes a local import, or an external import (from a different entry-point or package) based on whether a module specifier is absolute or relative. Using absolute paths internally can therefore be troublesome.

> Absolute Paths can be achieved with tsconfig.json and the corresponding path mapping.

The usage of tsconfig path mappings can be problematic for a library, as those path mappings won't generally be available in an app that consumes the library (it has to repeat them in the app's tsconfig). It can only work if the path mappings line up with the library name and scope.

**Comment by LastDragon-ru** [comment]
> The usage of tsconfig path mappings can be problematic for a library

Yep, it is, because ts doesn't replace paths while emitting js 😥 (https://github.com/microsoft/TypeScript/issues/15479).

> It is generally a good idea to only use relative imports 

Relative imports are unreadable, the `../../../../../../../../../../../../Component` is really terrible so I really don't understand how people may like it.... But this issue was created because absolute imports work without any problems inside Angular apps and there are no warnings about absolute paths in https://angular.io/guide/creating-libraries. So I was surprised when start migrating from one big app into app + libs and seen "No name was provided for external module 'xxx'" 😌

**Comment by flash-me** [comment]
> The usage of tsconfig path mappings can be problematic for a library, as those path mappings won't generally be available in an app that consumes the library (it has to repeat them in the app's tsconfig). It can only work if the path mappings line up with the library name and scope.

Never claimed it otherwise. The average developer shouldn't have the need to bother with path mappings at all. 

However, some folks maintain the opinion, that It's a good idea to refactor an application into separate libraries within the same repo. Apparently they see a bigger benefit than the overhead the libraries come respecting the additional build steps . 

Another valid, but barely known, use case is when working with [UMD format](https://github.com/flash-me/angular-micro-frontends/tree/a2c46defd76df7369b1e837fe8113a0b04b9d38a). This way, the paths don't matter anymore at runtime. Instead, it works with the UMD id's. I'm currently even playing around with ESM format, which works pretty well. By using `importmaps`, we can easily re-map the import paths according to my needs at runtime, too. Even though it's still a draft, you can polypill it for every major browser. 

B2T:
The reason why I mentioned the path mappings is because nearly no one, who opens an issue, wants to hear that the underlying problem is usually something else and that they wouldn't have the issue at all, if they would have applied best practices. I mean, an import like 
```
../../../../../../../../../../../../Component
``` 
doesn't happen overnight. Regardless of whether the webpack build supports absolute paths, people should have started to think about structure, cohesion, complexity, etc. **long before** arriving such circumstances. 

Seems like Conway's law is still a common challenge 💩

cheers
flash ⚡

**Comment by LastDragon-ru** [comment]
> additional build steps

This is another big issue.

>  I mean, an import like ../../../../../../../../../../../../Component doesn't happen overnight.

Actually, you cannot avoid ugly paths with multiple '..' inside them. In a big application you will see a lot of:

```
import {FilterComponent} from '../../../../../../../shared/mypkg/controls/filter.component';
```

In a very small lib you still will see:
```
import {AppError} from '../../../../Types/AppError';
```

no matter how you will organize the code, unuseful '..' will be always here 🤷‍♂️

**Comment by mlc-mlapis** [comment]
@LastDragon-ru Hmm, @flash-me mentioned **path mappings** as a solution, where the local relative paths are used just inside one lib, and it means that the deep is mostly one, two, or tree level as maximum. Cross lib imports are then always very simple because you use the libs identifier name.

**Comment by LastDragon-ru** [comment]
> that the deep is mostly one, two, or tree level as maximum

@mlc-mlapis , as you can see I already have four levels for really small lib 🤷‍♂️

> local relative paths are used just inside one lib

That's what I'm talking about: the library must use local relative paths for **own** files or you will get totally unuseful/confusing "WARNING: No name was provided for external module". There is no information about this in docs.

<details>
<summary>Real-world example/problem</summary>

I just wanted to split a big old app, that uses absolute imports (`import {FilterComponent} from 'shared/mypkg/controls/filter.component';`), into small parts.  So I read https://angular.io/guide/creating-libraries and thought "seems I can just copy files into `packages/mypkg` and everything will work, cool". Nope. Instead of app+mypkg, I got only a "WARNING: No name was provided for external module". External? Module? What?! 😕 And as I see now there is only one way to use separate lib(s) is to refactor the whole app to use relative paths. It is definitely not what I expected...
</details>

**Comment by mlc-mlapis** [comment]
@LastDragon-ru OK, I understand your problem now. 👍 But finally, the conclusion seems logical, doesn't it?

**Comment by LastDragon-ru** [comment]
@mlc-mlapis, IMHO, if angular supports absolute paths (paths mapping) itself then ng-packagr should support them too)

**Comment by flash-me** [comment]
@LastDragon-ru Path Mappings are supported by ng-packagr. In order to understand the underlying issue, some context is needed:

- By doing this, importing from these mapped paths will be treated as **externals** (like if you would import sth. from node_modules)
- This means btw, that these imports **won't** be included in your angular library
- The term "name" form the warning here refers to `UMD ID's`. Beside ESM and FESM Formats, [APF](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) specifies also `UMD` bundles to be included.
- The UMD ID of a package will be used to assign a property for `globalThis` (`window` for browsers), where the name of the property will be the UMD ID and the value are all the public exports of your library (e.g. here: `window['xxx']`)
- Now when another library imports yours, then your UMD ID can be provided, so the another library knows how the property is called for `globalThis`
- The **issue** here is, that `ng-packagr` cannot know under which UMD ID the path mapped imports will be attached to. Said that, it will 'guess' a 'name' and **thankfully** warns the user about that. 

**Recap**
- If you are going to publish your library, consumer will have to import also the path mapped stuff, which are not bundled in your library
- To **define the UMD ID of your library**, set the [`umdId`](https://github.com/ng-packagr/ng-packagr/blob/master/src/ng-package.schema.json#L80) property in your **ng-packagr config**.
- To **provide UMD ID's from other libraries**, you need to set key/value pairs in a [`umdModuleIds`](https://github.com/ng-packagr/ng-packagr/blob/master/src/ng-package.schema.json#L58) object in your **ng-packagr config**., wheree key is the import identifier and the value the UMD ID of that library.
- If you are not going to use UMD bundles (default angular app does not), then you don't need to bother with all this. 


### *To get away from the warning, just provide the same identifier you have used in the path mappings in your ng-packagr config*


Real world example project (which I already linked in my previous reply):
- The path mappings are defined [here](https://github.com/flash-me/angular-micro-frontends/blob/a2c46defd76df7369b1e837fe8113a0b04b9d38a/tsconfig.json#L21) for a shared library, which is used by other libraries / apps
- The shared library itself defines an UMD ID [here](https://github.com/flash-me/angular-micro-frontends/blob/a2c46defd76df7369b1e837fe8113a0b04b9d38a/projects/shared/package.json#L9)
- The other libraries are provided with the UMD ID of shared [here](https://github.com/flash-me/angular-micro-frontends/blob/a2c46defd76df7369b1e837fe8113a0b04b9d38a/projects/first/package.json#L11)

This is also the proof, that path mappings are supported correctly 😉

cheers
flash ⚡

**Comment by flash-me** [comment]
> This is another big issue (+ i18n and ivy support).

Can't say anything about i18n, but compiling libraries with ivy is already possible. In the current state however, publishing ivy compiled libraries is not recommended, since backwards compatibility is not guaranteed. 

> Actually, you cannot avoid ugly paths with multiple '..' inside them. In a big application you will see a lot of:
> 
> ```
> import {FilterComponent} from '../../../../../../../shared/mypkg/controls/filter.component';
> ```

Deep Imports paths are a good indication for hierarchical component structures. Most often (doesn't mean always) this is a result of bad design  and/or hardcoupled relations between components. While this is not always an issue (e. g. a lists and its items), this will likely lead to complexity, more dependencies, lower flexibility and sometimes even performance problems. 

> In a very small lib you still will see:
> 
> ```
> import {AppError} from '../../../../Types/AppError';
> ```
> 
> no matter how you will organize the code, unuseful '..' will be always here 🤷‍♂️

It's not about the  `.. ` per se, but how many of them are chained. The last time I had walk up three directories was a good year ago? Same day I ensured that this will be discussed in the next tech talk. 

Anyway. I'm not saying it is bad or that people should avoid this... I just have seen a lot, and often they were code smells, sometimes even circular dependencies. It's really no fun solving them. 

cheers
flash ⚡

**Comment by LastDragon-ru** [comment]
@flash-me, thank you for your explanation. Unfortunately,

> To get away from the warning, just provide the same identifier you have used in the path mappings in your ng-packagr config

seems [doesn't work](https://github.com/LastDragon-ru/ng-packagr-1757/commit/3327e0d19c1e2d93b9f187d9e3a8adf0da926820)

<details>

```
$ ng build my-lib
Building Angular Package
******************************************************************************
It is not recommended to publish Ivy libraries to NPM repositories.
Read more here: https://v9.angular.io/guide/ivy#maintaining-library-compatibility
******************************************************************************

------------------------------------------------------------------------------
Building entry point 'my-lib'
------------------------------------------------------------------------------
✔ Compiling TypeScript sources through NGC
✔ Bundling to FESM2015
⠋ Bundling to UMDWARNING: No name was provided for external module 'projects/my-lib/src/lib/my-lib.service' in output.globals – guessing 'myLib_service'
WARNING: No name was provided for external module 'projects/my-lib/src/lib/my-lib.component' in output.globals – guessing 'myLib_component'
WARNING: No name was provided for external module 'projects/my-lib/src/lib/my-lib.module' in output.globals – guessing 'myLib_module'
✔ Bundling to UMD
✔ Minifying UMD bundle
✔ Writing package metadata
ℹ Built my-lib

------------------------------------------------------------------------------
Built Angular Package
 - from: /project/tmp/my-workspace/projects/my-lib
 - to:   /project/tmp/my-workspace/dist/my-lib
------------------------------------------------------------------------------
```
</details>

> IMHO, if angular supports absolute paths (paths mapping) itself then ng-packagr should support them too)

I just meant that ng-packagr probably should replace absolute own imports to relative imports while building and should not treat them as externals (because they are not external and TS cannot do that (yet; I hope)).

**Comment by flash-me** [comment]
@LastDragon-ru You may want to fix the typo 😄 in your [tsconfig.json](https://github.com/LastDragon-ru/ng-packagr-1757/blob/master/tsconfig.json#L19) it is written with a hyphen.
![image](https://user-images.githubusercontent.com/5240450/104225104-3a732280-5446-11eb-90c5-9d7a1586a7f9.png)

cheers
flash ⚡

**Comment by LastDragon-ru** [comment]
![image](https://user-images.githubusercontent.com/1329824/104759407-4a0da680-5779-11eb-95a7-6bb0d50c4cd9.png)

A bit unusable 😅 Anyway, thank you 😀

**Comment by flash-me** [comment]
> ![image](https://user-images.githubusercontent.com/1329824/104759407-4a0da680-5779-11eb-95a7-6bb0d50c4cd9.png)
> 
> A bit unusable 😅 Anyway, thank you 😀

Indeed! I wasn't expecting this, neither. This is really annoying tbh. 
Ng-packagr is treating them as externals even though they are in the same compilation root I guess.

cheers
flash ⚡
