### ISSUE TITLE
Multi library in a monorepo that depend on one another issues

### ISSUE THREAD

**Issue by slavoroi** [ng-packagr/ng-packagr#1819]
## Type of Issue

```
[] Bug Report
[x] Feature Request
```

## Description

An ability to build a library 'libA' that depends on library 'libB' in the same mono repo without building library 'libB' and depending on it's dist folder.

#### Expected Behavior

In case we build a library that depends on another local library it should look for it's public-api.ts for it's types.
It should be implemented like angular implements the application build. 
When we build an app called 'app' (with the angular compiler) that depends on a local library 'libA', the application is being built successfully without building the libraries (so i guess it does it in memory).

#### Additional Information
For example, `tsc` does this successfully for our node ts based libraries in a monorepo by using `types` attribute in the package.json without any hacks in tsconfig.json.

An example of a project structure:
projects
├── libA
├── libB
├── app

#### Current errors
`Cannot find module 'libA'`
OR 
` 'rootDir' is expected to contain all source files.` when trying to manipulate rootDir.

**Comment by alan-agius4** [comment]
> In case we build a library that depends on another local library it should look for it's public-api.ts for it's types.
It should be implemented like angular implements the application build.
When we build an app called 'app' (with the angular compiler) that depends on a local library 'libA', the application is being built successfully without building the libraries (so i guess it does it in memory).

This is done using TSC path mappings, which is also not the recommended approach (
See: https://angular.io/guide/creating-libraries) as libraries should always be built prior of consumption because the library and application build pipeline are seperate.

What happens when using path mappings as that the library is compiled as part of the application. (Think of it like a folder under your `src/app`).

Building dependent libraries is not really in scope of ng-packagr, as that is more of the job of an orchestrator build tool such as Bazel that has the knowledge of how to build a library and in which order.

**Comment by slavoroi** [comment]
I tried using paths and it didn't work.
Anyone, ill continue with the hack of building the dependent libraries before to dist folder.
This creates an optimization issue of building unnecessary libraries when they were not change.
Thanks for the anwer.

**Comment by slavoroi** [comment]
I tried using paths and it didn't work.
Anyone, ill continue with the hack of building the dependent libraries before to dist folder.
This creates an optimization issue of building unnecessary libraries when they were not change.
Thanks for the answer.

**Comment by slavoroi** [comment]
I tried using paths and it didn't work.
Anyone, ill continue with the hack of building the dependent libraries before to dist folder.
This creates an optimization issue of building unnecessary libraries when they were not change.
Thanks for the answer.

**Comment by alan-agius4** [comment]
> I tried using paths and it didn't work.
> Anyone, ill continue with the hack of building the dependent libraries before to dist folder.
> This creates an optimization issue of building unnecessary libraries when they were not change.
> Thanks for the anwer.

You can use Bazel or NX to avoid re-building unchanged libraries.

**Comment by slavoroi** [comment]
im using lernawhich doesnt work for us.
