### ISSUE TITLE
Cant share code between libraries: rootDir is expected to contain all source files

### ISSUE THREAD

**Issue by MickL** [ng-packagr/ng-packagr#1841]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/cli or @ng-packagr/ng-packagr

### Description
When developing libraries it seems to be impossible to share code between them. E.g. two libraries may use the same interfaces. But as soon as importing something from outside of the libraries root folder (./projects/*) the build fails with error:

> rootDir is expected to contain all source files

Example: 

```
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib
```

Export a service to client app in `./projects/my-lib/src/lib/public_api.ts`:

```
export * from './lib/my-lib.module';
export * from './lib/my-lib.service';
```

Create a file `./projects/shared.ts`:

```
export interface Hello {
 world: string;
}
```

Import this file in exported service `./projects/my-lib/src/lib/my-lib.service.ts`.

What I tried:
- Setting `rootDir` or `rootDirs` in tsconfig.json does not have any effect.
- Setting `paths` in tsconfig.json does not change the error

### Describe the solution you'd like
Any solution importing a file from outside the library (e.g. I do share TypeScript interfaces with the Node.js backend) would be great! I searched for hours finding no solution.

I expected  everything imported to be part of the bundles.

**Comment by MickL** [comment]
There is also ng-packagr/ng-packagr#1264 which does not seem to describe the same problem as far as I see

**Comment by JoostK** [comment]
Continuing here from your comment in angular/angular-cli#19831:

> A library can be self contained no matter if it imports from outside of its root folder. A common example is that is it allowed to import from node_modules. In my opinion if it is forbidden or not should be decided by the developer.

Importing from `node_modules` is similar to what I meant by capturing the shared interfaces in a library of its own. That library can then indeed be consumed from another library that depends on those interfaces, which does indeed not sacrifice the "standalone" characteristics.

Are you importing the `shared.ts` file using a relative import from within the library, something like `'../../../shared.ts'`? That is becomes a problem for libraries if they are shipped to NPM, as that relative path then falls outside of the package boundary such that it won't be available.

If, on the other hand, you are using an absolute module path together with path mappings (which I have since learned is the case from https://github.com/ng-packagr/ng-packagr/issues/1264#issuecomment-763805156) then there's two challenges to deal with:

1. The imported file (`shared.ts`) has to be included for library consumers somehow, after the library has been installed into `node_modules`. How could files not inside of the root dir be contained within the package, as that is required to make them available to consumers?
2. The path mapping has to be registered in a consuming application, as without it only regular Node resolution rules are taken into account. This means that the absolute import is resolved from `node_modules/*name*`, but that thus requires that the content is actually found there.

The above two problems are resolved if `shared.ts` is bundled in a library of its own; this solves 1 as that library can then be distributed, making `shared.ts` available, and it avoids 2 as the library would then in fact reside inside `node_modules` under its name, making it discoverable by other libraries using regular Node module resolution rules (without needing path mappings).

**Comment by MickL** [comment]
With "bundled in a library of its own" do you mean to create an Angular Library, build it, publish to npm and import from node_modules? If so I wonder why can I import from node_modules but not from a TypeScript path? Also I do have at least two shared libaries: One for shared within Angular libraries and one for shared with backend. What if I would have 5 oder 10 shared libraries?

I import the shared file with paths: `import { MyInterface } from '@shared-with-backend';`. 

Then in tsconfig.json I have:

```
"paths": {
      "@shared-with-backend": [
        "../shared/src"
      ],
      "@shared-with-backend/*": [
        "../shared/src/*"
      ],
}
```

And in shared/index.ts I export everything:

```
export * from './admin.constants';
export * from './admin.interfaces';
export * from './client.constants';
```

If I do `import { MyInterface } from '@shared-with-backend';` I would expect it to be part of the final bundle, and not be still referenced. The same happens in the Angular app.

The only solution I can think of is making a pre-build script that copies the interfaces from the shared folder in each of my library folders.

**Comment by MickL** [comment]
To clearify the desired behavior: I want to import something from outside (in my case only interfaces, constants, enums, etc.) that should be bundled in the library on build.

**Comment by JoostK** [comment]
> With "bundled in a library of its own" do you mean to create an Angular Library, build it, publish to npm and import from node_modules?

Correct, I do mean to bundle that in a separate library. 

> If so I wonder why can I import from node_modules but not from a TypeScript path?

Imports are not "materialized"; they remain imports in the generated library code using their exact module path as was in the original TS source file. In APF (Angular Package Formats) you'll also find FESM bundles which are indeed bundles of multiple source files; this is done using Rollup and I believe it only includes files under a root dir, and consider anything outside said dir as external.

> Also I do have at least two shared libaries: One for shared within Angular libraries and one for shared with backend. What if I would have 5 oder 10 shared libraries?

One thing to consider is to just have (secondary) entry-points, not full packages. This allows code to be shipped in a single package while still providing distinct units of code to be reused in other packages/entry-points.

> What is the purpose of an Angular project that contains multiple libraries but cant share any code? If I do share code, ofcourse I expect it to be bundled with each library on build.

As mentioned before, "bundling" isn't really a concept for libraries, only for applications. The FESMs can be seen as bundles but they are limited to a self-contained directory structure, as otherwise the problems I introduced before start to arise.

> For your questions:
> 
> I import the shared file with paths: `import { UserDto } from '@shared-with-backend';`.
> 
> Then in tsconfig.json I have:
> 
> ```
> "paths": {
>       "@shared-with-backend": [
>         "../shared/src"
>       ],
>       "@shared-with-backend/*": [
>         "../shared/src/*"
>       ],
> }
> ```
> 
> And in shared/index.ts I export everything:
> 
> ```
> export * from './admin.constants';
> export * from './admin.interfaces';
> export * from './client.constants';
> ```
> 
> If I do `import { MyInterface } from '@shared-with-backend';` I would expect it to be part of the final bundle, and not be still referenced. The same happens in the Angular app.

Yeah, what really happens is that the `@shared-with-backend` import path will remain as-is in the generated library code; it won't be "inlined" in any way. That does indeed happen in apps, as then _everything_ is bundled together by Webpack.

> The only solution I can think of is making a pre-build script that copies the interfaces from the shared folder in each of my library folders and import them with './*'

Copying/moving the files to a well-known place _within_ the library is indeed a viable option, and I suspect the most pragmatic one. I would suggest to copy the files into a secondary entry-point of the library and import them using the published NPM name of your library.

It's a bit hard for me to offer more tangible advice, as I can't fully judge your situation. I.e. are you actually intending to ship NPM packages, or are you just using libraries for code separation? If the latter is true, you may want to look into Nx.

**Comment by MickL** [comment]
Hey, thanks for your answer! I do understand now why it is not working (because imports stay unresolved). This may change my feature request to be able to bundle things in the built library, just as with assets.

For my personal situation:
I do build multiple Angular libraries in one Angular project, each will be published in private npm modules. The npm modules will be consumed by different private Angular apps. The libraries use interfaces, constants, enums shared with other libraries in the same Angular project and also interfaces shared with backend libraries (Node.js) which follow the same pattern (will be published to private npm registry).

E.g. there is an admin-library that contains all services for admins (like auth/login, api calls etc) and will be consumed by multiple Angular Apps. The admin-library uses interfaces like UserDto, User, UserRole, etc. that are also used by other libraries in the same Angular project and in the backend built in Node.js within the same Git repo.

**Comment by MickL** [comment]
> I would suggest to copy the files into a secondary entry-point of the library and import them using the published NPM name of your library

I am not sure what you mean by secondary entry points and then import?

**Comment by MickL** [comment]
After further and further investigation I would like to close this issue. As @JoostK mentioned dependencies will not be built in the library and rather be provided by the client that uses the library. It makes no sense to build shared code in each library. Instead I now have a shared package published to a private npm package that each library consums as a peerDependency. The client library needs to provide this package.

In addition [Lerna](https://github.com/lerna/lerna) comes in handy for a monorepo, keeping track of local libraries and automatically symlinking them. For further reading on how to handle monorepo's with lerna: https://izifortune.com/share-angular-libraries-with-lerna/
