### ISSUE TITLE
[feature request] support jsonc format config like `angular.json`

### ISSUE THREAD

**Issue by JounQin** [ng-packagr/ng-packagr#1896]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Align to `angular.json` for comments

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            11.2.4
@angular/compiler:     11.2.3
rollup:                2.39.1
typescript:            4.2.2
```

**Comment by SchnWalter** [comment]
You should open this on the [Angular CLI](https://github.com/angular/angular-cli) repository, ng-packagr doesn't have anything to do with that file, it never uses it directly, the library builder part of the cli passes info down to ng-packagr.

**Comment by JounQin** [comment]
I mean `ng-package.json`

**Comment by SchnWalter** [comment]
The thing is, ng-packagr uses [avj](https://github.com/ajv-validator/ajv) to validate the provided values against a JSON schema, and that validator is respecting the RFC-8927 and comments are not part of that specification. Unless you can convince the avj team to add a flag to get around RFC-8927, this feature will not be possible, but I doubt that they will do that.

Also, `package.json` doesn't support comments and `ng-package.json` is just one of the ways to define a package and `ng-package.json` is tiny in comparison to angular.json or package.json, so I don't really see a reason to spend the resources to implement such a feature especially because it goes against a proven standard and it would be a half-backed solution (you can't do anything about the `package.json` file).

**Comment by JounQin** [comment]
I think we can use some module to load jsonc content first then pass the value through `avj`, that should not be difficult.

A consist way same as `tsconfig.json` or `angular.json` would be great.

**Comment by alan-agius4** [comment]
This is a good request and can be done quite easily.
