### ISSUE TITLE
export 'default' (imported as 'core_1') was not found in '@angular/core'

### ISSUE THREAD

**Issue by ams-itm** [ng-packagr/ng-packagr#210]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```
## Versions
``` 
ng-packagr: v1.5.0-rc.1
node: v6.11.0
@angular: v4.4.6
rxjs: 5.5.0
zone.js: 0.8.18
```
## Description

When packaging my library i get the following warning: 
```
'default' is not exported by 'node_modules\redux\es\index.js'
'default' is imported from external module 'rxjs/add/operator/let' but never used
'default' is imported from external module 'rxjs/add/operator/distinctUntilChanged' but n
'default' is imported from external module 'rxjs/add/operator/map' but never used
'default' is imported from external module 'rxjs/add/operator/filter' but never used
'default' is imported from external module 'rxjs/add/operator/switchMap' but never used
```

and when using my library in an application, i get the following warnings: 
```
"export 'default' (imported as 'core_1') was not found in '@angular/core'
```

Here's my setup:
ng-package.json
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "src": "lib",
  "dest": "dist/lib",
  "workingDirectory": ".ng_build",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "oidc-client": "./node_modules/oidc-client/dist/oidc-client.min.js",
      "rxjs/add/operator/let": "Rx.Observable.prototype"
    }
  }
}

```
public_api.ts_ 

`export * from './my-lib/my-lib.module'`

tsconfig: 
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/src",
    "baseUrl": "src",
    "paths": {
      "my-lib": [
        "dist/lib"
      ]
    },
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

```

I haven't been able to reproduce the issue in an example app
and I cannot make any sense of this but I hope you might. 
Thanks

**Comment by IThordGray** [comment]
Hi there,
I have the same issues.
If any help is available, it will be greatly appreciated.
Regards

**Comment by DavidParks8** [comment]
try changing your externals to 
```json
"externals": {
   "oidc-client": "oidc-client",
   "rxjs/add/operator/let": "Rx.Observable.prototype"
}
```

**Comment by ams-itm** [comment]
Hi @DavidParks8 . I tried what you suggested, unfortunately it didn't have any effect.

**Comment by ams-itm** [comment]
@IThordGray have you been able to reproduce the issue in an example app? Or do you have any idea what it might be ?

**Comment by andrepesi** [comment]
Hi @ams-itm . Did you got a solution ?

**Comment by ams-itm** [comment]
Hi @andrepesi. No, I have not.  If somebody could reproduce the issue it would be great.
Perhaps @dherges could pitch in?

**Comment by andrepesi** [comment]
@ams-itm I has created a new project, without "rxjs" dependencies and the error not happened. I am sure that error is about external dependencies references .

**Comment by ams-itm** [comment]
@andrepesi I agree. Could you provide this example project? It would help a lot!

**Comment by Gandii** [comment]
@ams-itm Experiencing the same problem, its related to angular-redux on how its is bundled i believe. seems it fails to import angular/core

**Comment by ams-itm** [comment]
Thanks for the response @Gandii. I solved it by packaging it using this guide (without ng-packagr) https://www.usefuldev.com/blog/post/publishing-a-library-from-an-angular-cli-project

**Comment by erieflin** [comment]
I'm having the same problem, unfortunately the useful dev link is not working for our implementation. Any ideas of potential fixes/ places to look for fixes would be appreciated.

**Comment by dherges** [comment]
Hi everyone,

do you have a GitHub repo so that I can reproduce the error?

Is it that an `export default ...` from TypeScript causes an error in rollup?

**Comment by dherges** [comment]
Hi everyone,

do you have a GitHub repo so that I can reproduce the error?

Is it that an `export default ...` from TypeScript causes an error in rollup?

**Comment by ams-itm** [comment]
@dherges I have not been been able to replicate the issue.

**Comment by tauinbox** [comment]
I got the same issue

```
WARNING in ./node_modules/ng-sp-lib/ng-sp-lib.js
29091:32-38 "export 'default' (imported as 'core_1') was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (C:\Projects\app\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Projects\app\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
```

**Comment by tauinbox** [comment]
the top of lib

`
import core_1, { ApplicationRef, ChangeDetectionStrategy, ChangeDetectorRef, Component, ComponentFactoryResolver, Directive, ElementRef, EventEmitter, Host, HostBinding, HostListener, Inject, Injectable, Injector, Input, NgModule, NgZone, Output, ReflectiveInjector, Renderer, TemplateRef, ViewChild, ViewContainerRef, ViewEncapsulation, forwardRef, isDevMode } from '@angular/core';
`

**Comment by IThordGray** [comment]
@ams-itm Sorry for replying only now. I changed gears completely and moved away from ng-packagr and followed some articles online, where I created my own packager seed. I didn't quite follow any of the threads there after.

**Comment by avatsaev** [comment]
Experiencing same issue here, not sure why exactly, we'll try to set up a repro repository as soon as we find the exact reason.

**Comment by avatsaev** [comment]
Ok I managed to prepro and pinpoint the exact use case for this error. I'll have the repro repository ready tomorrow at the latest. This thing wasn't easy to chase down very obscure error.

**Comment by avatsaev** [comment]
Sorry, I was able to reproduce this on two projects at work, the problem was with interface imports from VideoGular2 library, but when I tried to repro on a simplified open source version (here: https://github.com/avatsaev/ng-packagr-issue210-repro), everything was compiling fine, I think it happens due to combination with some other third party libs, I'm not sure which one(s) yet, I'll keep trying them one by one and I'll update here when I find it.

**Comment by avatsaev** [comment]
I think it's due to some third party libraries not respecting the Angular Library Format, so the imports you use from the lib, screws with the angular compiler (or webpack).

Here a solution I've found to debug, find out which lib breaks the transpilation, and fix the problem.

Suppose I have my-lib project that compiles with ng-packagr into dist/lib folder

After compilation in `dist/lib/my-lib.js` there is a problem with imports (core is not imported correctly):

![](https://i.imgur.com/ZvupfVI.png)

- Fist step is to figure out which lib is breaking everything so just control+F and look where core is used:

![](https://i.imgur.com/pUapnJW.png)

So one of the imports from TimeAgoPipe library is breaking the compilation

- Project wide search (ctrl+shif+f 'time-ago-pipe') I only import from time-ago-pipe lib once:

![](https://i.imgur.com/wSAz04n.png)

So the solution in this case is to add the entire import path into externals in ng-package.json (if you have other imports from this lib add them too):

![](https://i.imgur.com/1D0nsWH.png)

After which everything compiles fine:

![](https://i.imgur.com/O3R7xmY.png)

The most confusing part of this bug is not knowing where the error comes from, because the ng-packagr packages the lib just fine, without warnings and spitting out an error.

**Comment by dherges** [comment]
Hi @avatsaev,

cool you figured out more! Is it possible for you to publish a repro on GitHub?

Does it originate from a `import * as core from '@angular/core'`?

**Comment by ybrodsky** [comment]
@avatsaev hit the spot. I followed his instructions and was able to solve it.

**Comment by jfox459** [comment]
Thanks you @avatsaev , this worked.

**Comment by markus-wa** [comment]
For me this happened because I didn't have my `compilerOptions.module` set in `tsconfig.json`, which resulted in `commonjs` being used as default (for targets `es3` or `es5`).

Setting it to `es6` fixed it for me.

Relevant part:
```json
{
  "compilerOptions": {
    "module": "es6"
  }
}
```

**Comment by harishrathor** [comment]
Thanks @markus-wa Your solution worked for me. 'es2015' worked for me. 
Angular Version: 8.2.14

`{
  "compilerOptions": {
    "module": "es2015"
  }
}`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
