### ISSUE TITLE
Support `tslib@~2.1.0`

### ISSUE THREAD

**Issue by wSedlacek** [ng-packagr/ng-packagr#2174]
https://github.com/ng-packagr/ng-packagr/blob/d363ea2f643f4819bef698ca25fe3dcd9682290c/package.json#L62

RxJS is still using `tslib@~2.1.0`, given that this is a peer dependency could the version be loosened up?

**Comment by alan-agius4** [comment]
The version that is used in RxJs is based on the TypeScript version that is used to compile it's package which is TypeScript 4.2. Probably in this case RxJs can update their dependency to `^2.1.0` since typically breaking changes in tslib only happen in major releases.

Angular 13 supports TypeScript 4.4 which requires a tslib version 2.3.0 or later. 

See: https://github.com/microsoft/tslib/releases/tag/2.3.0
