### ISSUE TITLE
Support esbuild

### ISSUE THREAD

**Issue by eichiflSICKAG** [ng-packagr/ng-packagr#2759]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description
As esbuild became stable with Angular 17, it would be nice to enable esbuild for ng-packagr as well.
Are there any plans or roadmaps?

relates to [2621](https://github.com/ng-packagr/ng-packagr/issues/2621)

**Comment by jcompagner** [comment]
does this case also fixed the problem i now encounter in my setup?

We have a project that includes "ckeditor" that is a js file that is generated by their tooling (what stuff you support and pay for and so on)
that generates 2 js files that i need to use/import.

Before esbuilder i forced that to be a dynamic import so that import was not handles by rollup (ng-packagr) when making the npm package, and the js files where just assets which where dynamically imported by the browser builder (webpack did that)

but now with esbuild that dynamic import doesn't work anymore for that project that i use as a npm package. 
(Would be nice to know how something like this: https://github.com/RtVision/esbuild-dynamic-import i could get working in the angular builder)

so what i did was make the dynamic import of that project an normal import (still lazy so with import() don't want to always load that initially). This way it should work for the esbuild where on the application where that project/package is used 
But the problem is that rollup makes of that js file then because of that import a directly an "ckeditor.mjs" file...
but it is not a "mjs" its not an ecma module, its a CommonJS thing so i need that wrapper around it that esbuild (and previously webpack) did generate..

So when i use that package as a source package (through tsconfig.paths) then it generates this:

```
import {
  __commonJS,
  __spreadProps,
  __spreadValues,
  __yieldStar
} from "./chunk-D2KWFTNG.js";

// packages/@servoy/smartdocumenteditor/src/assets/lib/ckeditor.js
var require_ckeditor = __commonJS({
  "packages/@servoy/smartdocumenteditor/src/assets/lib/ckeditor.js"(exports, module) {
```

I guess i have to do this statically, so generate upfront that commonJS conversion to a module..  I can't just use that generated file itself because of the "./chunk-D2KWFTNG.js"; in it..
