### ISSUE TITLE
Unit test is only running for the main packages, but it ignore the spec files in other sub-packages

### ISSUE THREAD

**Issue by MurhafSousli** [ng-packagr/ng-packagr#2811]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

I have a library with sub-packages, the directory look like this:

![image](https://github.com/ng-packagr/ng-packagr/assets/8130692/56449201-92f3-4792-b0ec-7c3ed1fbec08)

The problem is when I run `ng test` it only run the spec files inside the main package inside `src` directory, but it ignores the spec files in the other sub-packages

#### Expected Behaviour

`ng test` should run all spec files inside all directories

#### Version Information

17.3.0

```
$ node_modules/.bin/ng-packagr --version

ng-packagr:            17.3.0
@angular/compiler:     17.3.0
typescript:            5.2.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
ng-packagr is not responsible for executing tests. However, this is likely due to a misconfiguration of the Angular CLI builder. I suspect that because you have spec files located outside of the `src` directory, you need to adjust the `include` option. Check out: https://angular.io/cli/test for more details.
