### ISSUE TITLE
Angular cli 5 AOT gives Module not found can't resolve .ngfactory

### ISSUE THREAD

**Issue by ghost** [ng-packagr/ng-packagr#285]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When building bundle with ng-packagr, installing it in Angular 5 app and then trying to AOT the application, the compiler throws the error that it's not able to find the referenced module.

#### How To Reproduce

1. "ng-packagr -p ng-package.json" bundle and npm publish
2. Install on new Angular 5 app (i.e. npm install)
3. Using ngTools webpack 1.8.0 AOT the application
4. Get errror. Example:
![image](https://user-images.githubusercontent.com/30442378/32872289-f43b3098-ca53-11e7-9970-1caa829d4adc.png)

#### Expected Behaviour

Should not display message since bundle is already build

#### Version Information

```
ng-packagr: v2.0.0-rc.0
node: v8.8.1
@angular: v5.0.1
rxjs: v5.5.2
zone.js: v0.8.18
typescript: v2.6.1
```

Workaround:
https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

Which is to include the library in the Include files of the tsconfig compilation

**Comment by mafalarz** [comment]
Adding symlinks: true to resolve section of webpack.config.js fixes the issue:

```
var config = {};
config.resolve = {
    extensions: ['.ts', '.js'],
    symlinks: true,
    modules: ['./node_modules']
};
...etc
module.exports = config;
```

**Comment by macjohnny** [comment]
removing `"rootDir": "./src",` from the `tsconfig.json` resolved the problem for us

**Comment by macjohnny** [comment]
we also have a similar issue with angular 4, which we weren't able to resolve, yet.

**Comment by macjohnny** [comment]
apparently, angular5 library builds are not compatible with angular4, see https://github.com/angular/angular/issues/19607

**Comment by dherges** [comment]
Please check your typescript version! You say you use  `typescript: v2.6.1`

There are known issues with that in Angular. For Angular v4, please use a TypeScript 2.3.x. For Angular v5, please use a TypeScript v2.4.x.

See https://github.com/angular/angular-cli/blob/ae53cb1319a2ef3b687cc0eeabb371ff5c048af0/packages/%40angular/cli/upgrade/version.ts#L170-L172

See #236

**Comment by noelmace** [comment]
I encountered this issue this day after a big refactoring, with TS 2.6 and the latest builds of angular-cli, devkit and ng-packagr.

It simply was a issue with some remaining imports from the wrong files. https://github.com/dherges/ng-packagr/issues/285#issuecomment-345268594 seems to be related to that, as it leads, by another way, to wrong imports too.

I don't think this issue is directly related to ng-packagr. Only the ngc error message is misleading.

**Comment by steveTripactions** [comment]
Ran into this error using a local npm group like @myorg. After much searching it turns out *.metadata.json in node_modules has the wrong "importAs" making ng serve --aot fail compilation. The fix is it has to be @myorg/mylibrary and this was being set from the field "name": "@myorg/mylibrary" in projects/mylibrary/package.json.

**Comment by raphael22** [comment]
Be careful to node_modules folder depth too.
Import from '@xxx/yyy' will work but not from '@xxx/yyy/zzz'
Even if you make sure metadata.json get the right path.
