### ISSUE TITLE
Version usable with angular cli schematics

### ISSUE THREAD

**Issue by sbabeal** [ng-packagr/ng-packagr#328]
## Type of Issue

[ ] Bug Report
[x ] Feature Request

## Description

Have you thought about creating a ng-packager version that works using schematics that would be compatible with the cli?

#### How To Reproduce

N/A

#### Expected Behaviour

N/A

#### Version Information

N/A

**Comment by dherges** [comment]
Hi @sbabeal,

sorry for my late response. What do you mean by "works using schematics?"

I'd say that ng-packagr is "compatible" with the cli. Compatible isn't the right term maybe. It's more of "complementary to" as you are free to use the Angular CLI and ng-packagr within the same project.

From chatting with Filipe there's the idea to do a `ng generate package-library` command which could either create the boilerplate to install ng-packagr in a cli project (add dependencies, add package.json for the lib, add npm script, ...) or even a schematic invoking ng-packagr so that you'd do `ng g package`…et voila, there's your `dist` folder!

**Comment by babeal** [comment]
@dherges - me as well. I wanted to respond with my other id but I got a new phone and sold the other one before I transfered my authenticator info and now i can't log in.  

What i was referring to was to create a set of schematics that would scaffold a demo site, the folder structure and create the tasks necessary to a library with the cli.  It would work the same way that nrwl/nx works and since I see on the github page that ngpackager works with nrwl/nx then i assume your familiar with them.  So it would be something like ```ng new"projectname" collection=ng-packagr-schematics``` or something like that.  It would be to help speed up new project creation as we are finding getting the configs correct is tough.

**Comment by dherges** [comment]
@babeal - Ok, it sounds like we are talking about two different ways of "CLI Schematics":

1.) A project scaffolding. Example:

```bash
$ ng generate lib my-awesome-lib
  create libs/my-awesome-lib/index.ts (xxx bytes)
  create libs/my-awesome-lib/package.json (xxx bytes)
  update package.json (xxx bytes)
# run `yarn add --dev ng-packagr`, if neccessary
```

After that, you will be able to do `yarn libs:my-awesome-lib:build` to execute `ng-packagr -p libs/my-awesome-lib/package.json`


2.) Run ng-packagr through schematics. Example:

```bash
$ ng generate build-my-lib --path libs/my-awesome-lib/package.json
```

This sounds interesting since schematics is built upon tree transformations and ships a filesystem abstraction – see https://github.com/angular/devkit/tree/master/packages/angular_devkit/schematics/src/tree – and is very similar to what ng-packagr is doing: piping a source set through a series of transformations. Point here is: imagine the angular packaging to be a very high level lambda expression like

```ts
(publicApiFile: string) => AngularPackageFormat
```

which is equivalent to

```ts
(input: FileSystemTree) => FileSystemTree
```

**Comment by alan-agius4** [comment]
Obsolete
