### ISSUE TITLE
Embed node modules in library bundles

### ISSUE THREAD

**Issue by oliveti** [ng-packagr/ng-packagr#368]
## Type of Issue

```
[ ] Bug Report
[ X] Feature Request
```

## Description

- I'm using `isNullOrUndefined`in my project from the package : `import { isNullOrUndefined } from 'util';`

- I have added to the externals the utili lib this way : 
```
 "lib": {
    "entryFile": "index.ts",
    "externals": {
      "@angular/material": "ng.material",
      "lodash": "_",
      "util": "util"
    }
  }
```

 - And now I get the following message during build :  

```
[0] Compiling to UMD
[0] Creating a browser bundle that depends on Node.js built-in module ('util'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
[0] Minifying UMD bundle
...
```

- I have included the library `rollup-plugin-node-builtins` but I do not know how I can integrate it with ng-packager.

Thank you.

```
ng-packagr: v2.x
@angular: v5.x.y
```

**Comment by alan-agius4** [comment]
Since I see you are using lodash, why not use lodash for such method? ‘_.isNil()’

**Comment by iamthechad** [comment]
I'm running into the same issue as @oliveti 

I'm getting `Creating a browser bundle that depends on Node.js built-in modules ('tty', 'util', 'events', 'stream', 'url', 'assert', 'http' and 'https'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins` from my build and my module fails in the browser because `process.version` doesn't exist.

I've tried adding `preferBuiltins` to `ng-package.json` with no luck.

**Comment by jdbranham** [comment]
I've created a PR that might help with this -
https://github.com/dherges/ng-packagr/pull/565

**Comment by dherges** [comment]
I renamed the title as I understand between the lines that node modules such as `fs`, `path` or similar should be written to the bundle files?!?

**Comment by gs-nchakravarthi** [comment]
Any update on this ??

**Comment by alan-agius4** [comment]
Closing since this is out-of-scope.
