### ISSUE TITLE
[feature] be able to change umdModuleId (& es moduleId ?)

### ISSUE THREAD

**Issue by paulsouche** [ng-packagr/ng-packagr#430]
## Type of Issue

```
[X] Feature Request
```

## Description

umdModuleId [is flattenedModuleId](https://github.com/dherges/ng-packagr/blob/master/src/lib/domain/ng-package-format.ts#L155) and it can't be changed.

What do you think of adding a key in `ng-package.json`

```json
{
  //...
  "lib": {
    "entryFile": "src/index.ts",
    "umdModuleId": "MyNameSpace.MySubNameSpace"
  }
}
```

And get the config value if present in `NgEntryPoint.umdModuleId getter`

This feature could be applied for each rollup bundle. What about create an esModuleId property for [es bundle](https://github.com/dherges/ng-packagr/blob/master/src/lib/entry-point-transforms.ts#L59) ?

I know it is not ideal and it makes config more complex but I can't figure out another solution...
  
#### Expected Behaviour

Be able to change rollup configuration & set moduleId in bundles.

#### Version Information

```
ng-packagr: latest
@angular/*: latest
typescript: latest
rxjs: latest
node: latest
npm/yarn: latest (both)
```

Let me know if you want a PR about this feature.

Anyway thanks for the great job.

**Comment by dherges** [comment]
Hi,

changing some of the internal tool options to alter the package's public API shape (let's consider the UMD module ID to be part of the public API) is an understandable use case. That said, I don't think this will make it into 2.x. The initial idea was [by design to hide implementation details and configuration of the toolchain](https://github.com/dherges/ng-packagr/blob/master/docs/DESIGN.md#configuration-and-customization).

I'd rather ask whether the flattened module ID is a "good enough" convention for the UMD module ID?

**Comment by paulsouche** [comment]
Hi,

thank you for your answer. My opinion is that flattened module ID is not a good enough convention because for dashed package names you will write `window['my-namespace']['my-module']`. It would be more elegant with `MyNamespace.MyModule`...

But as for the configuration, I'm not the only one involved here.

Thank you again for the great job.

**Comment by paulsouche** [comment]
OK no problem.

**Comment by dherges** [comment]
Hm hm ... i could live by making it optional to override the umd id. I still think an auto value is superior and don't understand why the umd id needs to be confiurable but I don't need to understand everything ;-)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
