### ISSUE TITLE
Backslashes are removed from packaged code

### ISSUE THREAD

**Issue by yonigo** [ng-packagr/ng-packagr#448]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
backslashes in html and css are removed from packaged code.

#### How To Reproduce

For html:
1 ) Create a component that has a string binding:  [message]="'User\'s Message'".
2 ) pack using ng-packagr
3)  try to use component in an angular-cli app. Received error:  Parser Error: Unexpected token 's' at..

For CSS:
1 ) Create a class with a content referencing a font:   content: "\f047";
2 ) pack using ng-packagr
3)  try to use component in an angular-cli app. the css is changed to ontent: "f047";

#### Expected Behaviour

backslashes should not be removed from css and html.

#### Version Information

```
ng-packagr: 2.0.0-rc.7
@angular/*: 5.1.2
typescript: 2.4.2
rxjs: 5.5.6
node: 6.9.5
npm/yarn: 1.3.2
```

**Comment by dherges** [comment]
Hi @yonigo,

can you check whether it is related to the following css replacement: https://github.com/dherges/ng-packagr/blob/master/src/lib/steps/assets.ts#L101-L102

It will be super helpful if you could provide a repro of your issue. Ideally, you add it to `integration/samples/<something>` in this repo and break that package's build.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
