### ISSUE TITLE
Allow `raw-loader` behaviour of loading raw files into TS files (supported in Angular CLI)

### ISSUE THREAD

**Issue by zakhenry** [ng-packagr/ng-packagr#514]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Ideally, most features that libraries might reasonably use, that are _already supported by angular cli default configuration_ should function with ng-packagr. To this end, the ability to load raw files would bring ng-packagr closer to this end goal.

There are a few reasons that loading a raw file into typescript are useful:
* Loading GLSL shaders for WebGL
* Loading static translation files
...etc

#### Expected Behaviour

Ideally the following syntax (which works) would also function with ng-packagr
```ts
//example.ts
import * as stockFragmentShader from 'raw-loader!./stock.frag';
import * as stockVertexShader from 'raw-loader!./stock.vert';
// [further code omitted]

    Effect.ShadersStore['StockPixelShader'] = stockFragmentShader as any;
    Effect.ShadersStore['StockVertexShader'] = stockVertexShader as any;
```
```
// shaders.d.ts
declare module 'raw-loader!*.frag' {
  var _: string;
  export default  _;
}
declare module 'raw-loader!*.vert' {
  var _: string;
  export default  _;
}
```

#### Version Information

```
ng-packagr: ^2.0.0-rc.11
@angular/*: ^5.1.1
typescript: ^2.4.2
rxjs: ^5.5.5
node: v8.0.0
npm: 5.5.1
```

**Comment by kyubisation** [comment]
I believe this can be achieved by inlining the raw files in the cache in analyse-sources.transform.ts, in resolveModuleNames and caching the changes in entryPoint.cache.analysisSourcesFileCache and entryPoint.cache.sourcesFileCache

e.g.
```ts
compilerHost.resolveModuleNames = (moduleNames: string[], containingFile: string) => {
    return moduleNames.map(moduleName => {
      // This would support imports like `import content from './file.html';`
      if (moduleName.endsWith('!text')) {
        ...
        Analyze the code with typescript and replace the import with a simple assignment.
        import content from './file.html'; => const content = `...`
        The changed content would be saved in the cache entries in entryPoint.cache.analysisSourcesFileCache and entryPoint.cache.sourcesFileCache
        ...
        return undefined;
      }
      if (!moduleName.startsWith('.')) {
        return undefined;
      }

      const { resolvedModule } = ts.resolveModuleName(
        moduleName,
        ensureUnixPath(containingFile),
        tsConfigOptions,
        compilerHost,
        analysisModuleResolutionCache,
      );

      return resolvedModule;
    });
  };
```

@dherges Is this something you would like to have in ng-packagr? If you approve of this, I will create a PR. Please give me a heads-up, if you would like a different architecture.

**Comment by alan-agius4** [comment]
Hi, thanks for your interest in this. 

But I am not really keen about this feature, and really we should not support anything which is not a proper module that TS and Tsickle support.

In past we added support to json modules since TypeScript added such support and probably this caused more misuses and lack of comparability with tsickle.

Also, I am not seeing the reason why such feature would be useful.

**Comment by kyubisation** [comment]
Thank you for the reply.

I have the following use case: In my company I manage the development of two angular libraries. One is for public facing websites, the other for internal business applications. Both libraries share quite a bit of code, but they differ in styling and some logic as well. What I would like to do, is extract common logic and templates into a core library. (mat-table and cdk-table do something similar)
I would like to keep the html in their own files, due to IDE support.

I do have a workaround, but it is a bit painful to use. It involes using `require('raw-loader!content.html')` and copying the html files into dist multiple times.

However, if you are opposed to this, I will accept that.

**Comment by alan-agius4** [comment]
Closing as this is not something we or the Angular CLI supports.
