### ISSUE TITLE
import javascript

### ISSUE THREAD

**Issue by Ts-alan** [ng-packagr/ng-packagr#540]
## Type of Issue

```
[ ] Feature Request
```

## Description
_for features:  My project contains from javascript import.But your typescipt compiler doesn't consist allow js=true.what should I do?

**Comment by dherges** [comment]
In the next release, you will be able to customize the default tsconfig through the programmatic API. Will that help you?

**Comment by Ts-alan** [comment]
Is it possible to do this now?May be on RC?

**Comment by deebloo** [comment]
@Ts-alan the latest rc (12) release has the new programatic api in it.

**Comment by Ts-alan** [comment]
Where can i see programatic api?End also i need embed legacy JavaScript library in my the my library.Is possible in not rc?

**Comment by deebloo** [comment]
you should just be able to say. ```import 'path-to-js-file.js```; I thought I saw the api in the README but let me double check. @dherges is the API documented yet?

**Comment by dherges** [comment]
No, no documentation on the programmatic API, yet.

**Comment by alan-agius4** [comment]
allowJs cannot be used if you are going to generate typings. So in reality it not such a good idea to have ‘allowJs’ in a library at least until Typescript 2.8

https://github.com/Microsoft/TypeScript/issues/7546

**Comment by erezws** [comment]
is it possibe at all to use an external js.file, in an exported module, using ng-packager? currently it is OK that it will be embedded or not.
in my public_api.ts file i wrote 'import * as a from '_____.js', but when running the packager I'm getting an error TS6143: " Module.... was resloved to ...... but '--allowJs' is not set.
would appricieate help on this

**Comment by alan-agius4** [comment]
Nope that is not something possible for the time being. 

It is not yet supported by typescript as right now you cannot import javascript files in typescript and generate declaration at the same time, you are only allowed to import js when not generting declaration which is usually at a consumer level rather than library level.


Check this issue: https://github.com/Microsoft/TypeScript/issues/7546

**Comment by erezws** [comment]
Hi,
first thank you for your answer.
the JS code is generated from a different module, but i will probably perform a change so it will generate TS code instead.

**Comment by dherges** [comment]
I marked it as wontfix as it's a typescript issue.

There are solutions at hand. One is to add a `*.d.ts` to the dependency's bundle and ship the `* .d.ts` in the dependency's npm package. Another is to write a custom `.d.ts` and reference it with a triple-slash directive.

**Comment by gravitypersists** [comment]
This is confusing - I can import arbitrary JS from a node module just fine and TS won't choke on that. What makes a generic JS module in my project any different? 

I was lucky enough to be able to get around this issue by the mere coincidence that the js modules I was trying to import are, by their nature, published right before I run this packaging.

**Comment by alan-agius4** [comment]
Closing as this is not an ng packagr bug but a TS issues as explained above.

**Comment by rplaurindo** [comment]
> What is the reason that you have javascipt source mixed with typescript?

In my case, I want to extend a built-in JS class. Something like ```Number.prototype.isOdd...```.

**Comment by neesonqk** [comment]
@alan-agius4 

https://www.typescriptlang.org/docs/handbook/modules.html#import -> Import a module for side-effects only

Though it is not recommended, but in some cases, to be able to use existing JS libraries or modules, we have to import those JS libraries etc. to set global states, however, seems that it is impossible to make it come true from here.

One example of this cases:

In our project, we need to use a generic module M which was created by JS, this module provides a lots third party JS plugins to extend its features as well as functions, in now days this M module has been converted to angular module which can be easily added by running `npm install M`, however, all those third party plugins are still with JS, and I don't see any possibility that the authors will make them TS compatible, since we are going to wrap the module M and the related plugins into a package, so we have to use side-effects import to work it around.
