### ISSUE TITLE
[v1] Support "from 'rxjs/operators'" syntax for lettable operators out of the box

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#569]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description

When using the rx operators as lettable operators (see https://blog.angularindepth.com/rxjs-understanding-lettable-operators-fe74dda186d3), the are imported from rxjs/operators e.g. as import { shareReplay, take, takeUntil } from 'rxjs/operators';

It would be nice if this would be supported oob.

**Comment by CarstenLeue** [comment]
Hi @alan-agius4, I was using the latest release "ng-packagr": "^1.6.0"

How do I reference the release candidate? When do you plan to go live?

**Comment by dherges** [comment]
When it's ready. It's ready then the blocker #443 is solved.

**Comment by alan-agius4** [comment]
You can do 

npm i ng-packagr@2.0.0-rc.12 —D

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
