### ISSUE TITLE
Enable fullTemplateTypeCheck and strictInjectionParameters by default ???

### ISSUE THREAD

**Issue by dherges** [ng-packagr/ng-packagr#718]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

fullTemplateTypeCheck: https://angular.io/guide/aot-compiler#fulltemplatetypecheck

strictInjectionParameters: https://angular.io/guide/aot-compiler#strictinjectionparameters

#### How To Reproduce

...

#### Expected Behaviour

...

#### Version Information

```
2.x
```

**Comment by alan-agius4** [comment]
@dherges what do you reckon? Shall we or shall we not?

**Comment by alan-agius4** [comment]
bump

**Comment by supperdsj** [comment]
how to set fullTemplateTypeCheck:false

**Comment by epelc** [comment]
Just ran into a nasty bug due to this. If you had two services in a sub package importing each other and being exported in an index.ts file(make everything else reference the index explicitly like you should).

Anyways ran into an error like this unless you enable `fullTemplateTypeCheck`.

```
------------------------------------------------------------------------------
Building entry point '@myorg/myproject/shared'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
WARNING: Circular dependency: dist/myorg/myproject/esm2015/shared/lib/services/index.js -> dist/myorg/myproject/esm2015/shared/lib/services/team.service.js -> dist/myorg/myproject/esm2015/shared/lib/services/index.js
WARNING: Circular dependency: dist/myorg/myproject/esm2015/shared/lib/services/index.js -> dist/myorg/myproject/esm2015/shared/lib/services/some-service.service.js -> dist/myorg/myproject/esm2015/shared/lib/services/index.js
Bundling to UMD
```

Only realized it because older libs were using the same pattern but a newly generated lib was giving circular dep errors and an issue preventing using `RouterModule.forChild()`.

> Function calls are not supported in decorators but 'RouterModule' was called

**Comment by alan-agius4** [comment]
Closed as this is obsolete.
