### ISSUE TITLE
[BUG] ng-packagr cannot load a less file from a component less file

### ISSUE THREAD

**Issue by Kamalen** [ng-packagr/ng-packagr#799]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

Importing a less or a CSS file contained in node_modules from a component cause a building error indicating "resource is missing"

        BUILD ERROR
        Ignoring local @import of "../../node_modules/sg-bootstrap/less/themes/standard/colors.less" as resource is missing

     
#### How To Reproduce

1. Create a component with a less style file
2. Import a less or css file provided in the node_modules folder
3. Try to package the application

#### Expected Behaviour

A succesful build

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.2
@angular/*: 5.2.9
typescript: 2.5.3
node: 8.9.1
npm: 5.6.0
```

**Comment by dherges** [comment]
Hi, please provide a reproduction.

**Comment by xmlking** [comment]
having same issue:
I am trying to implement angular wrapper for `FilePond` lib. my goal is to reuse css provided by   `FilePond`  developer by importing it into `scss` instead of copy&past the css. 
 
How to reproduce?
1. Checkout:
https://github.com/xmlking/ngx-filepond
2. Uncomment this line https://github.com/xmlking/ngx-filepond/blob/master/packages/ngx-filepond/src/filepond.component.scss#L1
3.  `npm run build:packages`

```
npm run build:packages

> ngx-filepond@1.0.6 build:packages /exp/Work/SPA/3rdparty/ngx-filepond
> ts-node tools/package

Building Angular Package
Building entry point '@pqina/ngx-filepond'
Rendering Stylesheets

BUILD ERROR
Ignoring local @import of "/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/filepond/dist/filepond.css" as resource is missing.
Error: Ignoring local @import of "/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/filepond/dist/filepond.css" as resource is missing.
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/postcss-clean/index.js:17:25
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/clean.js:109:9
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:26:64
    at loadOriginalSources (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:26:14
    at applySourceMaps (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/apply-source-maps.js:34:5)
    at Object.callback (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:25:12)
    at doInlineImports (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:200:25)
    at inlineLocalStylesheet (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:330:10)
    at inlineStylesheet (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:211:5)

ngPackagr build failed Error: Ignoring local @import of "/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/filepond/dist/filepond.css" as resource is missing.
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/postcss-clean/index.js:17:25
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/clean.js:109:9
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:26:64
    at loadOriginalSources (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:26:14
    at applySourceMaps (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/apply-source-maps.js:34:5)
    at Object.callback (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:25:12)
    at doInlineImports (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:200:25)
    at inlineLocalStylesheet (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:330:10)
    at inlineStylesheet (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:211:5)
Error building filepond Error: Ignoring local @import of "/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/filepond/dist/filepond.css" as resource is missing.
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/postcss-clean/index.js:17:25
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/clean.js:109:9
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:26:64
    at loadOriginalSources (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
    at /exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:26:14
    at applySourceMaps (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/apply-source-maps.js:34:5)
    at Object.callback (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:25:12)
    at doInlineImports (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:200:25)
    at inlineLocalStylesheet (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:330:10)
    at inlineStylesheet (/exp/Work/SPA/3rdparty/ngx-filepond/node_modules/clean-css/lib/reader/read-sources.js:211:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! ngx-filepond@1.0.6 build:packages: `ts-node tools/package`
npm ERR! Exit status 111
npm ERR! 
npm ERR! Failed at the ngx-filepond@1.0.6 build:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyz/.npm/_logs/2018-04-29T23_13_00_845Z-debug.log
```

**Comment by liliom55** [comment]
I get the same error but when I want to import css file to less file of component.


my-component.less
`@import '../../../node_modules/ngx-bootstrap/datepicker/bs-datepicker.css';
`
Version Information:
"@angular/core": "^5.2.0",
"typescript": "~2.5.3",
"@angular/cli": "~1.7.4",
"ngx-bootstrap": "^2.0.4",
"ng-packagr": "^2.4.2",

**Comment by xmlking** [comment]
If you are using angular-cli , `@import '~filepond/dist/filepond.css';` works for `ng serve` without any modification 
Then problem is we cannot package using ng-packagr

**Comment by alan-agius4** [comment]
@xmlking, in the application it works due to the fact that it is using `webpack` to resolve and inline the resources.

I had a look at your repo, and I found out that the problem is not related to `ng-packagr` but rather [clean-css](https://github.com/jakubpawlowicz/clean-css) It's unable to resolve an css import file to be inline correctly when it's absolute (at least on `Unix` based `OS`. I have opened an issue with them https://github.com/jakubpawlowicz/clean-css/issues/1027.

Just to give you some background, while you are not using an absolute path, when you use `~` these paths will be resolved to an absolute path, which in return clean-css will try to inline if the file is not `.scss` and thus was compiled with `libsass`.

Unfortunately you have 3 factories that contribute to this issue;
1) Unix Based OS
2) CSS import
3) Absolute path

@Kamalen If you want to embed CSS inside lines, the path should be relative to the `process.cwd()` rather than the less file path. This is again a limitation from [clean-css](https://github.com/jakubpawlowicz/clean-css) which is https://github.com/jakubpawlowicz/clean-css/issues/1029

**Comment by proAppleEater** [comment]
We had a similar issue. We fixed it. Posting in case this could help your case.

We had an import from bootstrap that is an node module.
We had @import "~bootstrap/scss/mixins";
This caused an error when trying to package using ng-packgr
In bootstrap, mixins is a folder AND a file (the file has a underscore _mixins.scss)
By specifying the underscore, this solved our issue : @import "~bootstrap/scss/_mixins";

**Comment by dandcrooks** [comment]
Any update on this issue? I have a similar issue trying to import a custom css file. Using the relative path to node_modules does not work.

`BUILD` ERROR
Ignoring local @import of "/home/.../notifications/node_modules/sass-common/dist/css/common-styles.min.css" as resource is missing.`

**Comment by qkhanhpro** [comment]
Currently we are having the issue, importing .CSS files to CSS based component also

**Comment by kagol** [comment]
Is there any solution？ @xmlking

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
