### ISSUE TITLE
[Feature Request] Support specifying which version of Angular Package Format to use

### ISSUE THREAD

**Issue by johnmcase** [ng-packagr/ng-packagr#814]
## Type of Issue

```
[ ] Bug Report
[X ] Feature Request
```

## Description

Currently each major version of ng-packagr only supports one version of the Angular Package Format, thus only targets one version of Angular:

- 1.x supports Angular 4
- 2.x supports Angular 5
- 3.x supports Angular 6

#344 Demonstrates that a package built targeting Angular 5 cannot be consumed by Angular 4.  As a library developer, I want my package to be consumed by as many versions of Angular as possible.

I know I can simply stick to the 1.x version of ng-packagr to target Angular 4, but I still want to have all of the other goodies and bug fixes that you are releasing with the latest version.

I propose having some kind of command-line switch or a property added to ng-package.schema.json that would support specifying which version of the APF I want to target.

**Comment by alan-agius4** [comment]
There are several reasons why I don't see this so not possible.

1) If you write code in Angular 4 for instance, it doesn't mean this will work with Angular 5. As there are a lot of factors such as RxJs version, Metadata generated by the compiler etc.

2) If you generate a package with lets say Angular Package Format 4, this won't be optimal for today, as the tools changed and so did the package format. So in that case you might be jeopardising your consumers as they might end up with larger bundle sizes or slower builds.

3) When you install the Angular Compiler you only install a single version, thus you can only build to a single version of Angular. Having installed for instance Angular Compiler 6, you cannot decide that you want to build for Angular 4. This not something which is possible. 

4) You should always encourage your users to migrate to the latest version and not have legacy code.

**Comment by cyrilletuzi** [comment]
Additional info from my experience as a library author:

> If you write code in Angular 4 for instance, it doesn't mean this will work with Angular 5. As there are a lot of factors such as RxJs version, Metadata generated by the compiler and so on.

Indeed, I have one distinct branch for each major version of Angular, with different code (for example, the v6 code use the new `providedIn` option in services).

So as already said, one option would be to have a directory for each major version with its own `node_modules` and its own version of `ng-packagr`.

> I know I can simply stick to the 1.x version of ng-packagr to target Angular 4, but I still want to have all of the other goodies and bug fixes that you are releasing with the latest version.

But for that, `ng-packagr` itself should follow LTS support, having one major version for each Angular major version, and back porting fixes.

**Comment by cyrilletuzi** [comment]
Which kind of fixes you include in LTS doesn't matter: even with only security fixes, you can still have to release a patch for older versions.

I suggest that each directory has its own `node_modules` *and* `ng_packagr`.

**Comment by dherges** [comment]
It's a matrix-compatibility thing.

Thoughts:
 1. Angular compiler 5 introduced metadata version 4. You cannot use metadata v4 in Angular 4 or prior.
 2. APF is a set of artefacts trying to support a broad range of tools. You will be able to create an APF 6 package that continues to work even with older versions of Angular as long as you used an "appropriate" compiler version. (In fact, the angular compiler has version constraints on typescript and that's why ng-packagr uses the typescript and angular compiler version that the user has already installed in the project).
 3. However, by the evolution of the Angular tooling some features (e.g. resource inlining) are being moved to the Angular compiler and thus (partially) removed from ng-packagr. At that point, ng-packagr has some version constraints on the angular compiler version (much like angular has on typescript).
 4. In turn, ng-packagr has version constraints on angular compiler and that has version constraints on typescript and on and on and on. At some point, it implies constraints on both authors and consumers of a library. Example: you won't get an Angular 6-compiled metadata v4 library to go get to work in an Angular 4 app.

As you said there are much factors influencing what versions are supported. That's where the "matrix-compatibility" term comes in. It's at most possible to support a limited set of version combinations. And it's impossible to make any guarantees or long-term plans for such upfront. Right now, ng-packagr@3 works with both ng@5 and ng@6 but who am I to know whether that continues in ng@7? I do not know the future 🌵 

Conclusion for me:
- If you want the new and shiny things, go update.
- v1 will continue to work
- v2 will continue to work

**Comment by dherges** [comment]
To picture that out: for now, you're able to run ng-packagr@3 and you will get APF6. You can use APF 6 with Angular 6 and Angular 5. But who am I to know whether APF7 will or will not work with \<Whatsoever\> \<Version\>?

If you're asking for APF "n" to be back-ported to v2 or v1, there's pull request welcome! 🎆

**Comment by dherges** [comment]
(un-intentionally closed/openend due to stupid comment 😆 )

**Comment by alan-agius4** [comment]
Closing as per above
