### ISSUE TITLE
Can't use baseUrl to have absolute imports in a library

### ISSUE THREAD

**Issue by victornoel** [ng-packagr/ng-packagr#916]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I generated a lib with angular-cli, the sources are directly under the `src` directory.

If I set the `baseUrl` in the tsconfig of my lib to `./src` and use absolute import in my lib (e.g., `import { FormatService } from 'locale/format.service';` instead of `import { FormatService } from './format.service';` in a file in the `locale` directory), the lib build fine, but then when angular tries to use it (it is configured via the `paths` in tsconfig.json), it fails with the following kind of error:
```
ERROR in Error during template compile of 'AppModule'
  Could not resolve locale/format.service relative to /home/victor/Codebases/frontend/target/dist-lib/my-lib.d.ts. in 'LocalizationModule'
    'LocalizationModule' contains the error at ../target/dist-lib/my-lib.ts(55,20).
target/dist-lib/locale/localization.module.d.ts(2,51): error TS2307: Cannot find module 'locale/format.service'.
```

#### How To Reproduce

Simply set a `baseUrl` pointing to the source directory and use absolute import instead of a relative one and use the lib in another app.

#### Expected Behaviour

This should work.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.0
@angular/compiler:     6.0.3
rollup:                0.59.4
tsickle:               0.29.0
typescript:            2.7.2
```

**Comment by alan-agius4** [comment]
Looks like you have a missing ‘.‘ in the locale path. Does this fix it?

Otherwise It would be greate that you provide a minimal reproduction.

**Comment by victornoel** [comment]
@alan-agius4 hehe, the whole point of the issue is to be able to express import in an absolute manner, i.e. without using a `.` at the beginning of the path.

See https://medium.com/@adrianfaciu/use-absolute-paths-for-module-imports-6e5ee9e94161 (first google answer on the subject, I haven't even read it in details) that explains the need and how it is usually solved with angular-cli.

I can do a repro, I will post it soon here.

**Comment by alan-agius4** [comment]
That is not valid in a library, as TypeScript will not rewire the paths when emitting, and thus the consumer will not be able to build when using the library and will have this issue.

See here: https://github.com/Microsoft/TypeScript/issues/9910#issuecomment-234729007

**Comment by victornoel** [comment]
@alan-agius4 I thought that ng-packagr was responsible of transforming the source code into something usable as a library. Can't it support absolute import and transform them to relative ones so that both the developer and the user are happy?

**Comment by alan-agius4** [comment]
Ng-packagr itself doesn’t do code transformation per see, it transpiles
your code using various tools such as ngc and packages it into multiple
formats using rollup.

**Comment by victornoel** [comment]
@alan-agius4 ok, thanks for the explanation :)

**Comment by vvasabi** [comment]
> Ng-packagr itself doesn’t do code transformation per see

Hmm... why not? I made a proof of concept (https://github.com/vvasabi/ng-packagr/commit/4a9e689224be826f872d9d1d5801fa33f46d2eed) and was able to get absolute paths working in my library. This library, which has 2 entry points, compiles successfully itself and can be consumed correctly by both an application or another library.

I made this POC because TypeScript already said that they wouldn’t fix it and users could achieve that result using a custom transformer. If ng-packagr does not do this when it reads and before it sends source code to downstream tsickle, rollup, etc., where else can the transformation be done?

Granted, my POC has hacks specifically to work around issues in tsickle and may not be suitable for inclusion into ng-packagr itself. However, I wonder if there can be a way to plug in custom code transformations, so those who need absolute paths will simply enable a plugin. (Or, maybe put the rewrite logic behind an experimental flag...)

In my case, I am consolidating common code from applications to shared libraries. Having the ability to use absolute paths, which the applications do use, will make this task a whole lot easier. After all, it makes no sense for one (good) thing to work in applications but not in libraries. (Heck, IntelliJ will even highlight long, ugly relative import paths to suggest the shorter, cleaner and sexier absolute paths!)

I will really appreciate if the ng-packagr team can reconsider supporting absolute paths in libraries!

**Comment by alan-agius4** [comment]
Hi @vvasabi, thanks for taking an interest in this. While indeed the above would work I have a couple of comments. 

TypeScript source transformation should happen using a transformer which is passed to the compiler. More info about this https://levelup.gitconnected.com/writing-a-custom-typescript-ast-transformer-731e2b0b66e6

That said, from ng-packagr perspective probably instead of having this transform inside of it, we should provide a way to allow users to hook up and provide their own transformers to the compiler. 

The main reason being is that we shouldn't provide features which are not supported by compiler and users should make the decision to go on an unsupported path and if eventually they change their build pipeline from `ng-packagr` to let's say `Bazel` this will not work.

Let's also remember that in applications they work because of the custom plugins/loaders in bundlers. If let's say you change your application bundler. You'd need to configure your bundler to interpret those paths. 

My recommendation would be use path mappings to resolve to modules identifiers that exists and not fictitious modules that you'd need to configure your bundler/loader how to resolve them. This will ensure that what you are writing is scallable and you when you want to change your build system you can do so without worrying that your pattern is not supported.

**Comment by stephaneeybert** [comment]
How to enjoy these non relative import statements within a library type project ? How to have these paths mappings exported and seen by a client application ?
