### ISSUE TITLE
Understand Dependencies

### ISSUE THREAD

**Issue by BamiGorengo** [ng-packagr/ng-packagr#932]
Sorry that i use the issue boar to get informations, but last time i ask on stackoverflow i didnt get any answere. 

I still dont understand the correct usage of the dependencies in the package.json. i just figure out that i cant add anything to the dependencies, because ng-packagr otherwhise throw errors. So i moved all to devDependencies... But now i have on my package on npm alot devDependencies listed, that are never used for the package... So where i list the "playground" dependencies?

And how i can add real dependencies? as exapmple: i use material2 components in my package. now i want that my package works without that people need to install material2 manualy. So how i can make that npm install material2 with the correct version i used for my lib as dependencie inside my packagefolder?

**Comment by alan-agius4** [comment]
In most cases peerDependencies are preferred over dependencies as the consumer of the library will decide which exact version to install and also with peerDependencies there are no risks of having duplicate dependencies.

That said, you can whitelist dependencies so that ng-package doesn’t throw an error for certain dependencies. Check here:https://github.com/dherges/ng-packagr/issues/716#issuecomment-378014856

For your example, material2, should be set both as a devDependency and peerDependency.

http://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/

**Comment by BamiGorengo** [comment]
Thanks for this informations! But how can i know wich dependency i can put in the `whitelistedNonPeerDependencies` ? and i need to move them from the peerDepen. or copy? (duplicate entries)

My package.json looks atm like this:

`{
    "name": "@devmonkeys/ngx-mark6",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build --prod",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "packagr": "ng-packagr -p ng-package.json"
    },
    "private": true,
    "dependencies": {},
    "peerDependencies": {
        "@angular/material": "^5.2.5",
        "@devmonkeys/scss-elements": "^1.1.4"
    },
    "devDependencies": {
        "angularfire2": "5.0.0-rc.6",
        "firebase": "4.10.0",
        "moment": "^2.22.1",
        "@angular/animations": "^5.2.10",
        "@angular/cdk": "^5.2.5",
        "@angular/cli": "~1.7.4",
        "@angular/common": "^5.2.0",
        "@angular/compiler": "^5.2.0",
        "@angular/compiler-cli": "^5.2.0",
        "@angular/core": "^5.2.0",
        "@angular/forms": "^5.2.0",
        "@angular/http": "^5.2.0",
        "@angular/language-service": "^5.2.0",
        "@angular/material": "^5.2.5",
        "@angular/platform-browser": "^5.2.0",
        "@angular/platform-browser-dynamic": "^5.2.0",
        "@angular/router": "^5.2.0",
        "@devmonkeys/scss-elements": "^1.1.4",
        "@types/jasmine": "^2.8.7",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "^6.0.109",
        "codelyzer": "^4.0.1",
        "core-js": "^2.5.6",
        "jasmine-core": "~2.8.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~2.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "^1.1.2",
        "karma-jasmine-html-reporter": "^0.2.2",
        "ng-packagr": "^2.4.4",
        "ngx-markdown": "^1.6.0",
        "protractor": "~5.1.2",
        "rxjs": "^5.5.6",
        "ts-node": "~4.1.0",
        "tslint": "~5.9.1",
        "typescript": "~2.5.3",
        "zone.js": "^0.8.19"
    },
    "ngPackage": {
        "whitelistedNonPeerDependencies": [
            "angular"
        ]
    }
}
`

**Comment by alan-agius4** [comment]
All angular dependencies should be both in `devDependencies` and `peerDependencies`. peerDependencies don't get installed.

For instance, from your `package.json`, some dependencies needs to be marked as peers as well, such as `moment`, `firebase` etc...

`devDependencies` - are dependencies used to build and bundle the library such as TypeScript.
`devDependencies + peerDependencies` - dependencies that are required by the library at runtime+ development time
`dependencies` - dependencies that are required by the library at runtime + development time

**Comment by BamiGorengo** [comment]
> dependencies - dependencies that are required by the library at runtime + development time

So i need to add material2 to the normal dependencies right?

**Comment by alan-agius4** [comment]
Nope, I suggest you read a bit more on what is the difference between a peerDependency and dependency and why should prefer the first over the last.

I just created a doc: https://github.com/alan-agius4/ng-packagr/blob/213f462fc8d607ee5cea44406162aca66e109421/docs/dependencies-whitelisting.md

**Comment by alan-agius4** [comment]
The answer is you shouldn’t.

Angular material should be configured and styled and application level and
not library level. From a library perspective, what you can do is use
angular material mixins and helpers, but not application related styles and
mixins.

If you care about you components being themeable and configurable You
should use theme files similar to the Angular Material approach (that said
you need to create a bit of a build system for that)

example:
https://github.com/alan-agius4/ng-mono-repo-starter/tree/master/packages/package-1/src

**Comment by alan-agius4** [comment]
Hi, in 99% of the cases, yeah you should definitely use `peerDependencies` if you are create a library. If you are consuming a library you should really be cautious when if it has a direct dependency. This of course doesn't apply for libraries that are meant to be used on the server.

This is because in web applications you'd always want to smallest possible bundle, and having 2 libraries that depends on different versions of the same library is not desired as it leads to increase in bundle size.

For example image you use 2 libraries and all of them depend on a different version of rxjs, you'll end up with 2 different versions of rxjs in the final bundle, which is not something that you would want.

Also, this is one of the reasons, why breaking changes shouldn't be done without a deprecation period. Developers and library maintainers should have enough time to remove the deprecated usages with the new implementations.

**Comment by alan-agius4** [comment]
I am not sure what to you mean and how using `dependencies` instead of `peerDependencies` will speed up development.

You can surely use dependencies instead of `peerDependencies` in your library if you wish to do so, no one is stopping you from doing that. But it's not the recommended pattern. `peerDependencies` are always preferred.

**Comment by rdhelms** [comment]
Also, many teams might be using angular libraries internally within their own npm registry. In that situation, they would have complete control over the versions of all their dependencies...and using dependencies would allow them to continually develop while periodically improving optimization via aligning dependency versions. Using peerDependencies would literally stop their development until the dependencies get aligned.

**Comment by rdhelms** [comment]
> I am not sure what to you mean and how using dependencies instead of peerDependencies will speed up development.

I think if you're not seeing that, then that's where we're fundamentally disagreeing haha
